Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2019-10, with the labels that each got.

#1349 OPS-28 - integration tests
  .gitignore
  .travis.yml
  Dockerfile
  Dockerfile.brb
  Dockerfile.n21
  Dockerfile.open
  Dockerfile.orig
  gulpfile.js
  package-lock.json
  package.json
  test/mocha/helper/login-helper.js
  views/account/settings.hbs
  views/administration/dashboard.hbs
  views/administration/forms/form-students.hbs
  views/administration/students.hbs
  views/administration/users_skipregistration.hbs
  views/calendar/forms/form-create-event.hbs
  views/courses/course.hbs
  views/courses/create-course.hbs
  views/dashboard/components/card_section.hbs
  views/dashboard/dashboard.hbs
  views/firstLogin/sections/email.hbs
  views/firstLogin/sections/password.hbs
  views/firstLogin/sections/thanks.hbs
  views/homework/evaluation.hbs
  views/lib/components/notification.hbs
  views/lib/components/table.hbs
  views/lib/loggedin.hbs
  views/news/edit.hbs
  views/pwRecovery/pwrecovery.hbs
  views/teams/edit-team.hbs
  views/teams/forms/form-add-member.hbs
  views/teams/members.hbs
  views/teams/team.hbs
Labels: ready to merge

#1429 render editor only
  views/topic/topic-edtr.hbs
Labels: ready to merge

#1431 CORS Update - Possibility to add unsafe-eval and unsafe-inline with *
  config/http-headers.js
  middleware/cors.js
  static/scripts/loggedin.js
Labels: ready to merge

#1430 Team seite update
  helpers/content/team.json
  static/images/team/clemens_tiedt.png
  static/images/team/luisa_schrott.png
Labels: ready to merge

#1416 SC-2099 Feathers v4 Auth Update - Activated not relevant for login / Cookie attributes for security
  controllers/login.js
  controllers/registration.js
Labels: ready to merge

#1434 SC-1148 Brute Force Prevention
  controllers/login.js
  static/scripts/login.js
  views/authentication/forms/login.hbs
Labels: ready to merge

#1439 fix reversing of order
  static/scripts/filter/feathers-filter.js
Labels: waiting for review

#1379 SC-1506 - remove old code (icon)
  controllers/files.js
  static/scripts/files.js
  views/files/files-grid.hbs
Labels: blocked_by_server_pr

#1454 verhindern, dass QR-Codes werden irrtümlicherweise auch für Lehrer erstellt werden
  controllers/administration.js
Labels: ready to merge

#1455 SC-2396 | vertical centering of initials in the user avatar
  static/styles/lib/loggedin.scss
Labels: ready to merge

#1457 integrate the nuxt client into the integration-test workflow
  .travis.yml
Labels: ready to merge

#1377 SC-1696 - filter default year
  controllers/administration.js
Labels: ready to merge

#1432 SC-2211 registration in old browsers
  controllers/registration.js
  gulpfile.js
  package-lock.json
  package.json
  static/scripts/base.js
  static/scripts/dataprivacy/dataprivacy.js
  static/scripts/dataprivacy/firstLogin.js
  static/scripts/dataprivacy/paginated_form.js
  static/scripts/dataprivacy/pin.js
  static/scripts/dataprivacy/pin_input.js
  static/scripts/dataprivacy/registration.js
  static/scripts/helpers/inputFromQuery.js
  static/scripts/helpers/inputLinking.js
  static/scripts/jquery/datetimepicker-easy.js
  views/lib/forms/paginatedForm.hbs
  views/registration/noIeInfo.hbs
  views/registration/pin.hbs
  views/registration/registration.hbs
  webpack.config.js
Labels: ready to merge

#1422 SC-2137 | added email input field for wish/problem form and more
  controllers/administration.js
  controllers/helpdesk.js
  static/scripts/loggedin.js
  static/styles/help/help.scss
  theme/n21/views/lib/help_menu.hbs
  views/help/contact.hbs
  views/help/forms/form_admin.hbs
  views/help/forms/form_bug.hbs
  views/help/forms/form_wish.hbs
  views/help/partials/help_contact.hbs
  views/lib/forms/form-contactAdmin.hbs
  views/lib/forms/form-contactHPI.hbs
  views/lib/help_menu.hbs
  views/lib/loggedin.hbs
Labels: ready to merge

#1448 SC-2146: add support mail to loggedout footer
  theme/brb/views/lib/extended_footer.hbs
  theme/n21/views/lib/extended_footer.hbs
  theme/open/views/lib/extended_footer.hbs
  views/lib/extended_footer.hbs
  views/lib/extended_footer_links.hbs
Labels: ready to merge

#1444 SC-1991 | added infos to last page of first Login
  controllers/firstLogin.js
  helpers/authentication.js
  static/images/firstLogin/welcome-1-fobi.svg
  static/images/firstLogin/welcome-1-student.svg
  static/images/firstLogin/welcome-2-help.svg
  static/images/firstLogin/welcome-banner.svg
  static/scripts/firstLogin.js
  static/styles/firstLogin/thanks.scss
  views/firstLogin/firstLogin.hbs
  views/firstLogin/partials/imports.hbs
  views/firstLogin/sections/thanks.hbs
Labels: ready to merge

#1469 SC-2446 | Displaying Alert Icon for dangerous files in student submissions
  static/scripts/homework.js
  static/styles/homework/submissions.scss
  views/homework/components/submission_uploaded_files.hbs
  views/homework/extended.hbs
  views/homework/submission.hbs
Labels: ready to merge
