Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2019-08, with the labels that each got.

#1342 SC-1170 Fix help dropdown
  static/styles/lib/loggedin.scss
Labels: ready_to_merge

#1323 Sc 1422 registration birthday
  .eslintrc.json
  controllers/registration.js
  static/scripts/administration/users_edit.js
  views/firstLogin/sections/birthdate.hbs
  views/firstLogin/sections/birthdate_U14.hbs
  views/firstLogin/sections/birthdate_UE14.hbs
  views/firstLogin/sections/birthdate_UE16.hbs
  views/registration/registration-parent.hbs
  views/registration/registration-student.hbs
Labels: ready_to_merge

#1330 Sc 1715 disable inputs on archived courses
  controllers/courses.js
  helpers/handlebars/helpers/index.js
  static/styles/courses/course.scss
  views/courses/components/groups.hbs
  views/courses/components/tasks.hbs
  views/courses/components/tools.hbs
  views/courses/components/topics.hbs
  views/courses/course.hbs
  views/courses/courseGroup.hbs
  views/courses/create-course.hbs
  views/courses/edit-course.hbs
  views/courses/edit-courseGroup.hbs
  views/courses/overview.hbs
Labels: ready_to_merge

#1333 SC-1750 populate bugfix
  controllers/administration.js
Labels: ready_to_merge

#1242 SC-1305-fix-filters-in-admin-area
  controllers/administration.js
Labels: blocked_by_server_pr

#1346 VUE-59 Make contact form on help page accessible via link
  controllers/help.js
  views/help/contact.hbs
  views/help/help.hbs
Labels: ready_to_merge

#1348 remove nightwatch
  .gitignore
  .travis.yml
  README.md
  diff.sh
  frontend_test.sh
  nightwatch.conf.js
  package-lock.json
  package.json
  test/nightwatch/courses/courses_create.js
  test/nightwatch/homework/homework_create.js
  test/nightwatch/login/login_demo_lehrer.js
  test/nightwatch/login/login_demo_schueler.js
  test/nightwatch/login/login_schueler.js
  test/nightwatch/news/news_create.js
Labels: waiting_for_review

#1347 SC-1791 show all classes during course creation
  controllers/administration.js
Labels: blocked_by_server_pr

#1365 remove ! in einwilligungserklärung
  views/registration/forms/einwilligungserklaerung.hbs
Labels: ready_to_merge
