Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2019-09, with the labels that each got.

#1370 SC-1801-disable-date-input-scrolling
  static/scripts/jquery/datetimepicker-easy.js
Labels: ready_to_merge

#1376 SC-1837 schuljahr bearbeiten bugfix (handlebars nesting)
  views/administration/forms/form-classes-edit.hbs
Labels: waiting_for_review

#1375 auto generate currentYear
  helpers/handlebars/helpers/index.js
  theme/brb/views/lib/footer.hbs
  theme/n21/views/lib/footer.hbs
  theme/open/views/lib/footer.hbs
  views/lib/footer.hbs
Labels: ready to merge

#1383 updated delete course message alert
  static/styles/courses/course.scss
  views/courses/edit-course.hbs
Labels: ready to merge

#1356 SC-1707-teacher-link-modal
  views/administration/forms/form-invitation-teacher.hbs
Labels: ready to merge

#1315 SC-1237 Fix-capped-end-of-calendarevents-in-dashboard
  controllers/dashboard.js
Labels: ready to merge

#1362 SC-1659-sort-students-by-last-name
  controllers/courses.js
  controllers/teams.js
Labels: ready to merge

#1358 fix help contact form keyboard navigation
  static/scripts/help/contactForm.js
Labels: ready to merge

#1386 Feature/sc-1755 - Removed headers on releases page
  controllers/help.js
  views/help/releases.hbs
Labels: ready to merge

#1378 SC-1881 - removed some student settings
  controllers/courses.js
  controllers/help.js
  controllers/homework.js
  controllers/welcome.js
  helpers/handlebars/helpers/index.js
  views/account/settings.hbs
  views/courses/overview-empty.hbs
  views/firstLogin/welcome.hbs
  views/help/partials/help_contact.hbs
  views/help/partials/help_nutzungshilfen.hbs
  views/homework/assignment.hbs
  views/homework/edit.hbs
  views/homework/evaluation.hbs
Labels: ready to merge

#1385 [SC-1975] Show all active courses in dropdown
  controllers/homework.js
Labels: ready to merge

#1388 fixed Intro: - removed unnecessary text - changed position of buttons
  static/scripts/loggedin.js
  static/scripts/login.js
  static/vendor/introjs/introjs.min.css
  views/authentication/forms/demo-login.hbs
  views/authentication/forms/login.hbs
Labels: ready to merge

#1409 fix description for LDAP self-service
  views/administration/forms/form-ldap-edit.hbs
Labels: ready to merge

#1402 Fix name of ermöglichen from Team to Groppenabgabe + linting
  views/homework/edit.hbs
  views/homework/extended.hbs
Labels: ready to merge

#1406 SC-1516 static Empfaenger.pdf in open for all schools
  theme/open/views/dataprivacy/privacy_weiterg-von-daten.hbs
Labels: ready to merge

#1408 SC-2133ff Add TOMs to privacy page
  theme/brb/views/dataprivacy/privacy.hbs
  theme/open/views/dataprivacy/privacy.hbs
  theme/open/views/dataprivacy/privacy_tom.hbs
  views/dataprivacy/privacy.hbs
  views/dataprivacy/privacy_tom.hbs
Labels: ready to merge

#1390 Update PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: waiting for review

#1393 Feature/SC-2046 added Button and Text in Helpdesk with link to team contact form
  views/administration/helpdesk.hbs
  views/help/contact.hbs
Labels: ready to merge

#1396 SC-1737 & SC-1726 Fix blank page issue if jwt is expired or accound of jwt is deleted
  helpers/authentication.js
Labels: ready to merge

#1412 SC-2161 | removed double login shown on mobile version in BRB / NBC
  theme/brb/views/authentication/home.hbs
  theme/n21/views/authentication/home.hbs
Labels: ready to merge

#1411 Feature/sc 2119 teacher visibility in n21
  controllers/account.js
  views/account/settings.hbs
Labels: ready to merge

#1404 fixed 'undefined' file remove
  views/files/files-grid.hbs
Labels: ready to merge

#1389 Feature/sc 1799 class successor
  controllers/administration.js
  views/administration/classes-edit.hbs
  views/administration/forms/form-classes-edit.hbs
Labels: waiting for review

#1410 SC-2123 | removed limit of courses displayed
  controllers/content.js
Labels: blocked_by_server_pr

#1413 Update Team Seite
  helpers/content/team.json
  static/images/team/tormod.png
Labels: ready to merge

#1423 SC-2300 Fix bug for homework without teamMembers
  controllers/homework.js
Labels: ready to merge

#1350 add sentry error reporting for client application
  app.js
  controllers/version.js
  helpers/authentication.js
  helpers/version.js
  package-lock.json
  package.json
  static/scripts/sentry.js
  test/mocha/helper/login-helper.js
  test/mocha/news/news.test.js
  theme/brb/views/lib/default.hbs
  theme/open/views/lib/default.hbs
  views/lib/default.hbs
  views/lib/sentry.hbs
Labels: ready to merge
