Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2020-09, with the labels that each got.

#2140 feature/SC-5706 - change language by registration
  CHANGELOG.md
  config/default.json
  config/default.schema.json
  controllers/registration.js
  helpers/i18n.js
  locales/de.json
  locales/en.json
  middleware/i18n.js
  static/scripts/dataprivacy/registration.js
  static/scripts/dataprivacy/user-registration.js
  static/scripts/helpers/cookieHelper.js
  views/lib/forms/form-change-language.hbs
  views/registration/registration-employee.hbs
  views/registration/registration.hbs
  views/template/registration.hbs
Labels: WIP

#2136 SC-6095 Add demo theme and adjust footer
  locales/de.json
  theme/demo/style.scss
  theme/demo/views/lib/footer.hbs
Labels: auto update, ready to merge

#2152 SC-5846 change wording Abmelden to Logout
  locales/de.json
Labels: auto update, waiting for review

#2142 SC-6254 change option to Wunsch
  views/help/contact-card.hbs
Labels: auto update, ready to merge

#2157 Hotfix SC-6526
  CHANGELOG.md
  package-lock.json
  package.json
  static/scripts/ckeditor/ckeditor-config.js
  static/scripts/ckeditor/plugins/ckeditor5-filebrowser/src/filebrowser.js
Labels: ready to merge

#2151 SC-6245 Enable students to invite other students to teams
  CHANGELOG.md
  controllers/teams.js
Labels: auto update

#2144 SC-6261 BRB Landing Page changes
  theme/brb/views/authentication/home.hbs
Labels: auto update, ready to merge

#2153 i18n SC-6529 Wrong language in team invitation
  locales/de.json
  views/help/partials/help_form_invite_external_members.hbs
Labels: auto update, i18n, ready to merge

#2161 SC-5500 - change wording Versuchen to lowercase
  locales/de.json
  theme/n21/views/authentication/home.hbs
Labels: auto update, ready to merge

#2166 i18n SC-6588 Quickfix wrong text footer
  theme/brb/views/lib/extended_footer.hbs
  theme/open/views/lib/footer.hbs
  theme/thr/views/lib/extended_footer.hbs
  theme/thr/views/lib/footer.hbs
  views/lib/extended_footer.hbs
Labels: i18n, waiting for review

#2135 SC-5989 - language switcher base component which can set the default la…
  CHANGELOG.md
  config/default.json
  config/default.schema.json
  controllers/account.js
  controllers/registration.js
  helpers/i18n.js
  locales/de.json
  locales/en.json
  middleware/i18n.js
  static/scripts/dataprivacy/registration.js
  static/scripts/dataprivacy/user-registration.js
  static/scripts/helpers/cookieManager.js
  test/mocha/helper/recurringEvents.test.js
  views/account/settings.hbs
  views/administration/school.hbs
  views/lib/forms/form-change-language.hbs
  views/registration/registration-employee.hbs
  views/registration/registration.hbs
  views/template/registration.hbs
Labels: auto update, ready to merge, waiting for review

#2167 SC-6552 - quote at end of footer in sc-card is deleted
  views/lib/components/sc-card.hbs
Labels: auto update, ready to merge

#2159 feature/SC-6095/add demo build
  Dockerfile.demo
  build.sh
Labels: auto update, ready to merge

#2163 SC-6545 – Shorten button text and add download icon
  locales/de.json
  views/homework/components/bulk-grading.hbs
Labels: auto update, ready to merge

#2141 Added padding left and right to the footer
  static/styles/homepage/homepage.scss
Labels: ready to merge

#2131 i18n SC-6361 Quickfix privacy policy
  views/firstLogin/sections/consent_updates.hbs
Labels: auto update, i18n, ready to merge, waiting for review

#2129 SC-5722 - intro text nbc
  locales/de.json
Labels: ready to merge

#2147 SC-6470 Added font-family attribute to login input -webkit-autofill
  static/styles/homepage/homepage.scss
  static/styles/homepage/login.scss
Labels: ready to merge

#2078 SC-5707 - login page language depending on browser lang
  CHANGELOG.md
  helpers/i18n.js
  middleware/i18n.js
  test/mocha/helpers/i18n.test.js
Labels: auto update, waiting for review

#2099 i18n SC-6161 Replacing "heading" with "headline"
  controllers/administration.js
  locales/de.json
  test/mocha/i18n/i18n.test.js
  theme/n21/views/lib/extended_footer.hbs
  theme/open/views/lib/extended_footer.hbs
  theme/thr/views/lib/extended_footer.hbs
  views/administration/dashboard.hbs
  views/administration/forms/form-ldap-edit.hbs
  views/administration/ldap-edit.hbs
  views/administration/ldap-schoolyear-start.hbs
  views/community/community.hbs
  views/content/store.hbs
  views/courses/create-course.hbs
  views/firstLogin/sections/birthdate.hbs
  views/firstLogin/sections/birthdate_U14.hbs
  views/firstLogin/sections/birthdate_UE14.hbs
  views/firstLogin/sections/birthdate_UE16.hbs
  views/firstLogin/sections/consent_updates.hbs
  views/firstLogin/sections/email.hbs
  views/firstLogin/sections/parent_intro.hbs
  views/firstLogin/sections/password.hbs
  views/firstLogin/sections/welcome.hbs
  views/firstLogin/sections/welcome_14-15.hbs
  views/firstLogin/sections/welcome_existing_geb14.hbs
  views/help/dashboard.hbs
  views/help/lern-nuggets.hbs
  views/help/partials/help_about.hbs
  views/help/partials/help_contact.hbs
  views/help/partials/help_first_steps.hbs
  views/help/partials/help_form_invite_external_members.hbs
  views/imprint/imprint_platform-intro.hbs
  views/imprint/imprint_rights.hbs
  views/lib/error_content.hbs
  views/lib/extended_footer.hbs
  views/registration/registration-employee.hbs
  views/registration/registration-parent.hbs
  views/registration/registration-student.hbs
  views/registration/registration.hbs
  views/template/registration.hbs
  views/topic/topic.hbs
Labels: auto update, i18n, ready to merge

#2146 remove ui for teachers to delete students
  controllers/administration.js
  views/administration/users_edit.hbs
Labels: waiting for UX review, waiting for review

#2172 SC-5668 - ghost universal component for every theme
  package-lock.json
  static/scripts/theme-blog.js
  theme/brb/views/authentication/home.hbs
  theme/n21/static/scripts/n21-blog.js
  theme/n21/views/authentication/home.hbs
  theme/open/views/authentication/home.hbs
  theme/thr/views/authentication/home.hbs
Labels: auto update, waiting for review

#2149 SC-5734 Bug Fix for participants pop up (Long names are wrongly dispalyed)
  controllers/administration.js
  static/styles/courses/course.scss
Labels: auto update, ready to merge

#2174 SC-6256 - focus on enter for login button on login page
  views/authentication/forms/login.hbs
Labels: auto update, ready to merge

#2177 SC-6710: fix errors in file.js
  static/scripts/files.js
  static/scripts/homework.js
Labels: ready to merge

#2178 SC-6604 - change users admin route
  controllers/administration.js
Labels: auto update, auto_merged

#2175 OPS-1109 removed deployment on testenvironment.
  deploy.sh
Labels: auto update, auto_merged

#2183 SC-6714 - max size in MB fix
  app.js
  controllers/help.js
  views/help/forms/form_bug.hbs
  views/help/forms/form_wish.hbs
Labels: auto update, ready to merge

#2200 SC-6800 - deleted name in sc-card next to open text
  views/lib/components/sc-card.hbs
  views/lib/forms/paginatedForm.hbs
Labels: waiting for review

#2162 SC-6566: i18n some more missing keys
  locales/de.json
  locales/en.json
  static/scripts/administration/school.js
  static/scripts/files.js
  static/scripts/topicEdit.js
  views/files/files-overview.hbs
  views/help/partials/login_failed_hint.hbs
Labels: auto update, i18n, waiting for review

#2095 SC-5963 Illustrations Create Course, Teams, Timeout Modal
  static/images/empty-states/add_people.svg
  static/images/empty-states/teams.svg
  static/scripts/autologout.js
  static/styles/courses/course.scss
  static/styles/courses/empty-state.scss
  static/styles/lib/forms/form-auto-logout-alert.scss
  views/courses/components/svg_create_course.hbs
  views/courses/create-course.hbs
  views/lib/components/svg_timeout_modal_default.hbs
  views/lib/components/svg_timeout_modal_error.hbs
  views/lib/forms/form-auto-logout-alert.hbs
  views/teams/overview-empty.hbs
  views/teams/svg_empty_teams.hbs
Labels: auto update, ready to merge

#2085 SC-5768 change illustrations onboarding
  static/images/firstLogin/welcome-1-fobi.svg
  static/images/firstLogin/welcome-1-student.svg
  static/images/firstLogin/welcome-2-help.svg
  static/images/firstLogin/welcome_screen.svg
  static/styles/firstLogin/firstLogin.scss
  static/styles/firstLogin/thanks.scss
  views/firstLogin/components/welcome_greeting.hbs
  views/firstLogin/partials/imports.hbs
  views/firstLogin/partials/svg_onboarding_1st_step.hbs
  views/firstLogin/partials/svg_onboarding_help.hbs
  views/firstLogin/partials/svg_onboarding_student.hbs
  views/firstLogin/partials/svg_onboarding_teacher.hbs
  views/firstLogin/partials/svg_onboarding_welcome.hbs
  views/firstLogin/sections/welcome.hbs
  views/firstLogin/welcome.hbs
Labels: auto update, ready to merge

#2097 SC-6137 Illustrations Error Pages
  static/scripts/dataprivacy/registration-link-validation.js
  static/styles/administration/dataprivacy.scss
  static/styles/lib/error.scss
  views/lib/components/svg_error_content.hbs
  views/lib/csrf.hbs
  views/lib/csrf_content.hbs
  views/lib/error_content.hbs
  views/lib/registration.hbs
Labels: auto update, ready to merge

#2199 Hotfix/1/SC-6637 - Fix QR code generation
  CHANGELOG.md
  controllers/administration.js
  package-lock.json
  package.json
  static/scripts/helpers/printQRs.js
Labels: waiting for review

#2210 SC-5963 Illustrations Timeout Modal
  static/styles/lib/forms/form-auto-logout-alert.scss
Labels: ready to merge

#2208 Hotfix: SC-6582: save messenger flag in course settings
  CHANGELOG.md
  controllers/courses.js
  package-lock.json
  package.json
Labels: waiting for review

#2196 move RC iframe higher to avoid colliding with matrix
  static/styles/teams/team.scss
Labels: ready to merge

#2179 SC-6602 fixing FAB icon in Tasks for mobile
  static/styles/homework/overview.scss
Labels: auto update, waiting for UX review, waiting for review

#2069 Feature/sc 5101/fix news order
  controllers/dashboard.js
  controllers/teams.js
Labels: ready to merge

#2214 remove unneeded populate
  controllers/homework.js
Labels: auto update, ready to merge

#2201 SC-6715 Inform about Rocket-Chat deprecation
  app.js
  config/default.schema.json
  config/global.js
  controllers/rocketChat.js
  controllers/teams.js
  locales/de.json
  locales/en.json
  static/images/messenger-info.svg
  static/scripts/deprecationInfoRocketChat.js
  static/scripts/messenger/welcome.js
  views/administration/school.hbs
  views/lib/loggedin.hbs
  views/teams/edit-team.hbs
Labels: ready to merge

#2212 Hotfix/3/sc 6762/fix evaluation file upload
  CHANGELOG.md
  app.js
  controllers/homework.js
  package-lock.json
  package.json
  static/scripts/homework.js
Labels: waiting for review

#2215 Hotfix/5/sc 6630 fix email validation for experts
  CHANGELOG.md
  locales/de.json
  package-lock.json
  package.json
  static/scripts/teamMembers.js
  views/teams/forms/form-invite-external-member.hbs
Labels: do_not_merge

#2206 Hotfix/SC 6836 html lang value
  controllers/dashboard.js
  controllers/files.js
  helpers/handlebars/helpers/index.js
  helpers/i18n.js
  locales/de.json
  locales/en.json
  middleware/i18n.js
  static/scripts/calendar.js
  test/mocha/account/account.test.js
  test/mocha/administration/administration.test.js
  test/mocha/app.test.js
  test/mocha/calendar/calendar.test.js
  test/mocha/classes/classes.test.js
  test/mocha/content/content.test.js
  test/mocha/courses/courses.test.js
  test/mocha/dashboard/dashboard.test.js
  test/mocha/files/files.test.js
  test/mocha/helper/login-helper.js
  test/mocha/helper/recurringEvents.test.js
  test/mocha/homework/homework.test.js
  test/mocha/link/link.test.js
  test/mocha/login/login.test.js
  test/mocha/login/superheroLogin.test.js
  test/mocha/news/news.test.js
  views/account/settings.hbs
  views/administration/school.hbs
  views/courses/courseGroup.hbs
  views/dashboard/dashboard.hbs
  views/files/files-overview.hbs
  views/help/partials/login_failed_hint.hbs
  views/homework/components/overview_card_template.hbs
  views/homework/edit.hbs
  views/homework/extended.hbs
  views/homework/overview.hbs
  views/homework/submission.hbs
  views/lib/loggedin.hbs
  views/news/article.hbs
  views/news/overview.hbs
  views/teams/topics.hbs
  views/topic/topic.hbs
Labels: WIP, i18n, waiting for review

#2207 Hotfix/1/SC-6823 - Fixed inserting media in comments for homework correction
  CHANGELOG.md
  package-lock.json
  package.json
  static/scripts/ckeditor/plugins/ckeditor5-filebrowser/src/filebrowser.js
  views/homework/assignment.hbs
  views/homework/evaluation.hbs
  views/homework/submission.hbs
Labels: waiting for review

#2194 update i18n mocha test
  locales/en.json
  test/mocha/i18n/i18n.test.js
Labels: auto update, i18n

#2219 SC-6614 - disable firstLogin for demo users
  config/default.schema.json
  controllers/firstLogin.js
Labels: auto update, waiting for review

#2222 hotfix/1/SC-6932
  locales/de.json
  locales/en.json
  static/scripts/jquery/datetimepicker-easy.js
  theme/n21/views/help/help.hbs
  views/administration/forms/form-classes-edit.hbs
  views/administration/forms/form-rss.hbs
  views/help/contact.hbs
  views/help/help.hbs
  views/homework/components/overview_card_template.hbs
  views/homework/edit.hbs
Labels: i18n, waiting for UX review, waiting for review

#2100 i18n Missing Translation Teams
  locales/de.json
  locales/en.json
  views/courses/courseGroup.hbs
  views/teams/forms/form-import-course.hbs
  views/teams/forms/form-import-topic.hbs
  views/teams/forms/form-tools.hbs
  views/teams/topics.hbs
Labels: auto update, i18n, ready to merge

#2211 SC-6611 Illustrations Landing Page
  static/images/home/advantage_1.svg
  static/images/home/advantage_2.svg
  static/images/home/advantage_3.svg
  static/images/home/advantage_4.svg
  static/images/home/advantages.svg
  static/images/home/hero.svg
Labels: auto update, do_not_merge

#2220 changed FEATURE_TEAMS_ENABLED variable flag to true by default
  config/global.js
Labels: auto update, ready to merge

#2232 Hotfix/5/sc 6940
  CHANGELOG.md
  helpers/i18n.js
  package-lock.json
  package.json
Labels: do_not_merge

#2218 SC-6598 - New dates not editable
  static/scripts/calendar.js
Labels: auto update, waiting for review

#2158 SC-6256: Login with Enter
  views/authentication/forms/login.hbs
Labels: auto update, ready to merge

#2228 hotfix/3/25.0.5/fix create etherpad without section name
  CHANGELOG.md
  package-lock.json
  package.json
  static/scripts/topicEdit.js
Labels: waiting for review
