Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2020-08, with the labels that each got.

#2049 SC-5917 Fix bug in LDAP activation
  CHANGELOG.md
  controllers/administration.js
  package-lock.json
  package.json
Labels: waiting for review

#2055 SC-5644: main skiplink fix a11y
  static/styles/lib/base.scss
Labels: a11y, ready to merge

#1885 i18n SC-4751 ADMINISTRATION
  locales/de.json
  views/administration/classes.hbs
  views/administration/classes_skipregistration.hbs
  views/administration/courses.hbs
  views/administration/dashboard.hbs
  views/administration/forms/form-account-password.hbs
  views/administration/forms/form-classes-edit.hbs
  views/administration/forms/form-classes-manage.hbs
  views/administration/forms/form-courses.hbs
  views/administration/forms/form-delete-alias.hbs
  views/administration/forms/form-delete-name.hbs
  views/administration/forms/form-delete-rss.hbs
  views/administration/forms/form-delete-user.hbs
  views/administration/forms/form-import.hbs
  views/administration/forms/form-invitation-student.hbs
  views/administration/forms/form-invitation-teacher.hbs
  views/administration/forms/form-ldap-edit.hbs
  views/administration/forms/form-message-owner.hbs
  views/administration/forms/form-problem.hbs
  views/administration/forms/form-remove-members.hbs
  views/administration/forms/form-rss.hbs
  views/administration/forms/form-students.hbs
  views/administration/forms/form-systems.hbs
  views/administration/forms/form-teachers.hbs
  views/administration/forms/form-teams.hbs
  views/administration/forms/form-terminate-school-year.hbs
  views/administration/helpdesk.hbs
  views/administration/import.hbs
  views/administration/ldap-edit.hbs
  views/administration/ldap-schoolyear-start.hbs
  views/administration/partials/data_protection_hint.hbs
  views/administration/school.hbs
  views/administration/students.hbs
  views/administration/teachers.hbs
  views/administration/teams.hbs
  views/administration/users_edit.hbs
  views/administration/users_registrationcomplete.hbs
  views/administration/users_skipregistration.hbs
  views/help/dashboard.hbs
Labels: i18n, ready to merge

#2056 Feature/sc 5949/fix a11y firstlogin
  views/authentication/forms/login.hbs
Labels: ready to merge

#2057 Merge pull request #2056 from hpi-schul-cloud/feature/SC-5949/fix-a11…
  views/authentication/forms/login.hbs
Labels: ready to merge

#2034 SC-5644 - qr code printing using keyboard only
  CHANGELOG.md
  static/scripts/base.js
  views/lib/loggedin.hbs
Labels: a11y, ready to merge

#2053 SC-5938 - Quickfix uncheck registrierunglink by default
  views/administration/forms/form-import.hbs
Labels: auto update

#2059 SC-5926: hide messenger options only using css
  views/administration/school.hbs
Labels: auto update, ready to merge

#1748 Fix help card2
  theme/n21/views/help/mail-card.hbs
Labels: ready to merge

#2065 fix spacing issue
  locales/de.json
Labels: i18n, waiting for review

#2061 SC-5957: removed visual focus from the main sections
  theme/brb/views/lib/extended_footer.hbs
  theme/brb/views/lib/footer.hbs
  theme/n21/views/lib/extended_footer.hbs
  theme/n21/views/lib/footer.hbs
  theme/open/views/lib/extended_footer.hbs
  theme/open/views/lib/footer.hbs
  theme/thr/views/lib/extended_footer.hbs
  theme/thr/views/lib/footer.hbs
  views/lib/extended_footer.hbs
  views/lib/footer.hbs
  views/lib/loggedin.hbs
Labels: a11y, waiting for review

#2063 SC-5957: removed visual focus from the main sections (a11y)
  theme/brb/views/lib/extended_footer.hbs
  theme/brb/views/lib/footer.hbs
  theme/n21/views/lib/extended_footer.hbs
  theme/n21/views/lib/footer.hbs
  theme/open/views/lib/extended_footer.hbs
  theme/open/views/lib/footer.hbs
  theme/thr/views/lib/extended_footer.hbs
  theme/thr/views/lib/footer.hbs
  views/lib/extended_footer.hbs
  views/lib/footer.hbs
  views/lib/loggedin.hbs
Labels: a11y, ready to merge

#2066 Hotfix SC-5954: configure messengers in teams
  CHANGELOG.md
  package-lock.json
  package.json
  views/teams/edit-team.hbs
Labels: waiting for review

#2068 Hotfix/3/sc-5948 international login
  CHANGELOG.md
  config/default.schema.json
  config/global.js
  controllers/login.js
  package-lock.json
  package.json
Labels: ready to merge

#2067 Feature/SC-5968
  locales/de.json
Labels: auto update, waiting for review

#2037 i18n SC-5336 Translation Administration LONG_TEXT
  controllers/administration.js
  locales/de.json
  static/scripts/topicEdit.js
  views/administration/forms/form-classes-edit.hbs
  views/administration/forms/form-classes-manage.hbs
  views/administration/forms/form-policy.hbs
  views/administration/forms/form-terminate-school-year.hbs
  views/administration/helpdesk.hbs
  views/administration/ldap-edit.hbs
  views/administration/partials/data_protection_hint.hbs
  views/administration/school.hbs
  views/administration/students.hbs
  views/administration/teachers.hbs
  views/administration/users_edit.hbs
  views/calendar/forms/form-create-event.hbs
  views/teams/forms/form-invite-external-member.hbs
Labels: i18n, waiting for review

#2015 i18n Mocha test for de.json
  test/mocha/i18n/i18n.test.js
Labels: i18n, waiting for review

#2040 SC-5687 - Dynamic illustrations
  static/images/empty-states/active_courses.svg
  static/images/empty-states/archived_courses.svg
  static/images/empty-states/assignments.svg
  static/images/empty-states/books.svg
  static/images/empty-states/books_empty.svg
  static/images/empty-states/groups.svg
  static/images/empty-states/tasks.svg
  static/images/empty-states/tools.svg
  static/images/empty-states/topics.svg
  static/styles/courses/course.scss
  views/courses/components/groups.hbs
  views/courses/components/svg_active_courses.hbs
  views/courses/components/svg_archived_courses.hbs
  views/courses/components/svg_groups.hbs
  views/courses/components/svg_tasks.hbs
  views/courses/components/svg_tools.hbs
  views/courses/components/svg_topics.hbs
  views/courses/components/tasks.hbs
  views/courses/components/tools.hbs
  views/courses/components/topics.hbs
  views/courses/edit-course.hbs
  views/courses/overview-empty.hbs
  views/courses/overview.hbs
Labels: auto update, ready to merge

#2017 [SC-5720] A11y for DataPrivacy
  locales/de.json
  static/scripts/dataprivacy/registration-link-validation.js
  theme/n21/views/dataprivacy/privacy.hbs
  theme/n21/views/dataprivacy/privacy_cookies.hbs
  theme/n21/views/dataprivacy/privacy_erh-persb-daten.hbs
  theme/n21/views/dataprivacy/privacy_logs.hbs
  theme/n21/views/dataprivacy/privacy_newsletter.hbs
  theme/n21/views/dataprivacy/privacy_priv-und-daten.hbs
  theme/n21/views/dataprivacy/privacy_rechte.hbs
  theme/n21/views/dataprivacy/privacy_verantw-stelle.hbs
  theme/n21/views/dataprivacy/privacy_verarb-persb-daten.hbs
  theme/n21/views/dataprivacy/privacy_weiterg-von-daten.hbs
Labels: a11y, auto update, ready to merge

#2054 SC-5928 a11y-partners
  static/styles/partner/partner.scss
  theme/thr/views/partner/partner.hbs
  views/partner/partner.hbs
Labels: a11y, auto update, ready to merge

#2041 SC-5806 first login
  locales/de.json
  theme/open/views/registration/forms/einwilligungserklaerung.hbs
  views/firstLogin/sections/email.hbs
  views/firstLogin/sections/password.hbs
  views/firstLogin/sections/thanks.hbs
Labels: a11y, auto update, ready to merge

#2073 SC-5605 add saveName to team files
  controllers/teams.js
Labels: ready to merge

#2072 Feature/sc 5838 prepare enable courseroute
  controllers/coursegroups.js
  controllers/courses.js
  controllers/oauth2.js
  controllers/teams.js
  controllers/topics.js
  locales/de.json
Labels: auto update, ready to merge

#1916 SC-4675 Update calendar.js
  gulpfile.js
  package-lock.json
  package.json
  static/scripts/calendar.js
  static/styles/calendar/calendar.scss
  static/styles/calendar/fullcalendar.min.css
  views/calendar/calendar.hbs
Labels: ready to merge, waiting for UX review

#2087 bugfix/missing keys i18n
  views/courses/create-course.hbs
  views/firstLogin/sections/password.hbs
  views/firstLogin/sections/thanks.hbs
Labels: ready to merge

#2075 i18n SC-6032 Quickfix wrong keys firstLogin
  locales/de.json
  views/firstLogin/sections/thanks.hbs
Labels: auto update, i18n, ready to merge

#2074 Feature/sc 3684 close consent route
  bin/www
  controllers/administration.js
  controllers/firstLogin.js
  controllers/login.js
  helpers/consentVersions.js
  test/mocha/account/account.test.js
Labels: auto update, ready to merge, waiting for review

#2089 SC-5470 updated csv_example.png
  static/images/csv_example.png
Labels: auto update, ready to merge

#2038 [SC-5827] A11y for Help page
  controllers/help.js
  locales/de.json
  static/scripts/help.js
  static/scripts/help/contactForm.js
  static/styles/help/help.scss
  theme/brb/views/help/people.hbs
  theme/open/views/help/people.hbs
  theme/thr/views/help/people.hbs
  views/help/confluence.hbs
  views/help/contact-card.hbs
  views/help/dashboard.hbs
  views/help/forms/form_bug.hbs
  views/help/forms/form_wish.hbs
  views/help/icon-card.hbs
  views/help/icon-link-group.hbs
  views/help/lern-nuggets.hbs
  views/help/partials/help_confluence_links.hbs
  views/help/people.hbs
  views/help/releases.hbs
  views/lib/help_menu.hbs
Labels: a11y, ready to merge

#2088 Feature/sc 6063/add evaluation delet function
  controllers/files.js
  static/scripts/homework.js
Labels: ready to merge

#2082 Hoftix 24.2.1 - SC-6012, SC-6125
  CHANGELOG.md
  package-lock.json
  package.json
  static/scripts/topicEdit.js
  theme/brb/views/help/mail-card.hbs
Labels: waiting for review

#1887 Make school selection be hidable #SC-4278
  locales/de.json
  static/scripts/login.js
  views/authentication/forms/login.hbs
Labels: ready to merge

#2077 SC-5775 - change wording on login page
  locales/de.json
  static/scripts/login.js
  test/mocha/dashboard/dashboard.test.js
  views/authentication/forms/login.hbs
Labels: waiting for review

#2058 SC-5951 - update mint-ec text on community page
  locales/de.json
  views/community/community.hbs
Labels: auto update, waiting for review

#2091 Quickfix - Update README.md
  README.md
Labels: waiting for review

#2101 SC-6158 - fix spacing between login and mehr optionen
  views/authentication/forms/login.hbs
Labels: ready to merge

#2104 SC-5927: Only show team messenger notification if the criteria are met
  controllers/teams.js
  locales/de.json
  views/lib/loggedin.hbs
Labels: auto update, ready to merge

#2052 SC-5915: homework dashboard
  locales/de.json
  static/scripts/homework.js
  static/styles/homework/homework.scss
  static/styles/lib/loggedin.scss
  theme/brb/views/lib/footer.hbs
  theme/n21/views/lib/footer.hbs
  theme/open/views/lib/footer.hbs
  theme/thr/views/lib/footer.hbs
  views/homework/components/overview_card_template.hbs
  views/homework/overview.hbs
  views/lib/components/pagination.hbs
  views/lib/footer.hbs
  views/lib/loggedin.hbs
Labels: a11y, auto update, ready to merge

#2115 SC-6248 Switch to the new admin student route
  controllers/administration.js
Labels: ready to merge

#2103 SC-6154 - header margin top and n21 logo fix
  theme/brb/style.scss
  theme/brb/views/lib/header.hbs
  theme/n21/style.scss
  theme/n21/views/lib/header.hbs
  theme/open/style.scss
  theme/open/views/lib/header.hbs
  theme/thr/style.scss
  theme/thr/views/lib/header.hbs
Labels: auto update, ready to merge

#2111 updated missing keys i18n
  locales/de.json
  static/scripts/calendar.js
  theme/brb/views/lib/extended_footer.hbs
  views/administration/forms/form-courses.hbs
  views/administration/forms/form-invitation-student.hbs
  views/administration/teams.hbs
  views/administration/users_edit.hbs
  views/courses/create-course.hbs
  views/courses/edit-course.hbs
  views/help/dashboard.hbs
  views/teams/team.hbs
Labels: auto update, i18n, waiting for review

#2093 Hotfix SC-5983 Rework TSP consent process
  config/default.schema.json
  controllers/firstLogin.js
  package-lock.json
  package.json
  views/firstLogin/components/welcome_greeting.hbs
  views/firstLogin/firstLoginShortened.hbs
  views/firstLogin/sections/thanks.hbs
Labels: waiting for UX review

#2113 SC-6250 Fix cookie attributes for chrome
  app.js
  config/default.json
  config/default.schema.json
  config/development.json
Labels: auto update, ready to merge

#2120 Hotfix/2/sc 6296
  CHANGELOG.md
  controllers/administration.js
  package-lock.json
  package.json
  static/scripts/administration/systems/ldap-edit.js
Labels: do_not_merge

#2105 SC-6238-a11y
  static/scripts/settings.js
  views/account/settings.hbs
  views/authentication/forms/login.hbs
Labels: a11y, auto update, ready to merge

#2112 SC-6019 - Having a tabbar for showing classes
  CHANGELOG.md
  controllers/administration.js
  locales/de.json
  static/scripts/administration.js
  static/scripts/tabbar.js
  views/administration/classes.hbs
Labels: auto update, waiting for UX review, waiting for review

#2109 SC-6166 - modal not showing class name on delete
  controllers/administration.js
  locales/de.json
  static/scripts/administration/users_edit.js
  views/administration/classes.hbs
  views/administration/courses.hbs
  views/administration/forms/form-delete-name.hbs
  views/administration/teams.hbs
  views/administration/users_edit.hbs
Labels: ready to merge

#2096 SC-1883 - Distinguish archived courses also in admin view
  controllers/administration.js
  static/styles/lib/tabbar/tabbar.scss
  views/administration/courses.hbs
Labels: auto update, waiting for review

#2005 [SC-5643] Dashboard A11y
  controllers/dashboard.js
  views/dashboard/components/homework_tiles.hbs
  views/dashboard/dashboard.hbs
  views/lib/components/sc-card.hbs
Labels: a11y, ready to merge

#2130 Hotfix/3/sc 6072 fix syncing schoolfeatures
  controllers/administration.js
  package-lock.json
  package.json
Labels: waiting for review

#2071 SC-5915: a11y homework details
  locales/de.json
  static/scripts/files.js
  theme/thr/views/lib/footer.hbs
  views/courses/components/tasks.hbs
  views/files/file-upload.hbs
  views/homework/components/course_overview_card_template.hbs
  views/homework/edit.hbs
Labels: a11y, auto update, ready to merge

#2132 SC-6380 - change link in impressum
  theme/open/views/imprint/imprint.hbs
  theme/thr/views/imprint/imprint.hbs
  views/imprint/imprint_rights.hbs
Labels: waiting for review

#2126 A11y Refinement
  theme/brb/views/lib/extended_footer.hbs
  views/help/dashboard.hbs
  views/help/icon-link-group.hbs
  views/help/lern-nuggets.hbs
  views/homework/components/overview_card_template.hbs
  views/lib/loggedin.hbs
Labels: a11y, i18n, ready to merge

#2134 Hotfix SC-6382
  CHANGELOG.md
  controllers/firstLogin.js
  package-lock.json
  package.json
Labels: waiting for review

#2107 SC-6086: a11y teams
  static/styles/lib/base.scss
  views/calendar/forms/form-create-event.hbs
  views/files/files-grid.hbs
  views/files/files.hbs
  views/files/forms/form-new-file.hbs
  views/lib/components/modal.hbs
  views/lib/components/sc-card.hbs
  views/lib/components/table.hbs
  views/lib/loggedin.hbs
  views/lib/sc-card_additionalInfo/memberCount.hbs
  views/team/team.hbs
  views/teams/edit-team.hbs
  views/teams/forms/form-file-permissions.hbs
  views/teams/forms/form-import-course.hbs
  views/teams/forms/form-import-topic.hbs
  views/teams/forms/form-invitation.hbs
  views/teams/forms/form-invite-external-member.hbs
  views/teams/forms/form-tools.hbs
  views/teams/overview-empty.hbs
  views/teams/team.hbs
  views/teams/topics.hbs
Labels: a11y, auto update, ready to merge
