Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2020-11, with the labels that each got.

#2269 Hotfix/1/SC-2710 - Custom Timezone
  app.js
  config/default.json
  config/default.schema.json
  controllers/administration.js
  controllers/calendar.js
  controllers/courses.js
  controllers/dashboard.js
  controllers/helpdesk.js
  controllers/homework.js
  controllers/news.js
  controllers/registration.js
  controllers/teams.js
  helpers/handlebars/helpers/index.js
  helpers/recurringEvents.js
  helpers/timesHelper.js
  locales/de.json
  locales/en.json
  middleware/datetime.js
  middleware/i18n.js
  package-lock.json
  package.json
  static/scripts/administration.js
  static/scripts/calendar.js
  static/scripts/helpers/AlertMessageController.js
  static/scripts/jquery/datetimepicker-easy.js
  static/scripts/news.js
  static/scripts/teams.js
  static/scripts/timezone.js
  static/styles/dashboard/dashboard.scss
  test/mocha/helpers/timesHelper.test.js
  test/mocha/i18n/i18n.test.js
  views/administration/administration.hbs
  views/administration/classes_skipregistration.hbs
  views/administration/forms/form-students.hbs
  views/administration/school.hbs
  views/administration/students.hbs
  views/administration/users_edit.hbs
  views/administration/users_skipregistration.hbs
  views/calendar/calendar.hbs
  views/calendar/forms/form-create-event.hbs
  views/courses/course.hbs
  views/courses/create-course.hbs
  views/courses/edit-course.hbs
  views/firstLogin/sections/birthdate.hbs
  views/firstLogin/sections/birthdate_U14.hbs
  views/firstLogin/sections/birthdate_UE14.hbs
  views/firstLogin/sections/birthdate_UE16.hbs
  views/homework/assignment.hbs
  views/homework/components/overview_card_template.hbs
  views/homework/edit.hbs
  views/lib/default.hbs
  views/lib/forms/form-date-input.hbs
  views/lib/forms/form-datetime-input.hbs
  views/news/edit.hbs
  views/registration/registration-parent.hbs
  views/registration/registration-student.hbs
Labels: auto update, waiting for review

#2313 adding trim before post email for recovery
  CHANGELOG.md
  controllers/pwrecovery.js
Labels: auto update, ready to merge

#2315 followup to correct naming
  locales/de.json
  locales/en.json
  static/scripts/files.js
Labels: auto update, ready to merge

#2305 SC-6662-private homework add data-testid
  CHANGELOG.md
  views/dashboard/components/homework_tiles.hbs
Labels: waiting for review

#2319 OPS-1297 - Add Changelog github action.
  .github/workflows/require_changelog.yml
  CHANGELOG.md
Labels: auto update, waiting for review

#2323 Bugfix/sc 7590
  CHANGELOG.md
  controllers/administration.js
Labels: do_not_merge, waiting for review

#2325 SC-7666 - translation key fix
  CHANGELOG.md
  views/administration/forms/form-rss.hbs
Labels: ready to merge, waiting for review

#2321 SC-7645 fixed team calendar timezone bug
  CHANGELOG.md
  controllers/teams.js
  static/scripts/teams.js
Labels: auto update, ready to merge

#2320 SC-7353 - fix course sharing
  CHANGELOG.md
  controllers/courses.js
Labels: auto update

#2328 Show correct age options while registration
  CHANGELOG.md
  locales/de.json
  locales/en.json
  views/firstLogin/firstLoginExistingUser.hbs
Labels: auto update, ready to merge

#2326 SC-7669 frontend datetime library
  CHANGELOG.md
  controllers/dashboard.js
  controllers/teams.js
  helpers/handlebars/helpers/index.js
  helpers/timesHelper.js
  static/scripts/administration.js
  static/scripts/administration/users_edit.js
  static/scripts/datetime/datetime.js
  static/scripts/helpers/AlertMessageController.js
  static/scripts/teams.js
  views/homework/assignment.hbs
  views/teams/team.hbs
Labels: auto update

#2329 bugfix/SC-7653
  CHANGELOG.md
  static/scripts/calendar.js
Labels: waiting for review

#2332 SC-7392 - copy paste of changes from develop for 7392 into release
  CHANGELOG.md
  locales/de.json
  locales/en.json
  static/scripts/calendar.js
  views/calendar/forms/form-create-event.hbs
Labels: auto update, ready to merge, waiting for review

#2333 SC-7453 - course team display fix
  CHANGELOG.md
  static/scripts/calendar.js
Labels: auto update, ready to merge, waiting for review

#2322 Feature/sc 5476 add one to one student chats
  CHANGELOG.md
  config/default.schema.json
  config/global.js
  config/http-headers.js
  controllers/administration.js
  helpers/authentication.js
  locales/de.json
  locales/en.json
  static/scripts/chatLoggedin.js
  views/administration/school.hbs
  views/lib/loggedin.hbs
Labels: auto update, ready to merge

#2335 SC-7571 - Implement a bulk call for generate registrationLink
  CHANGELOG.md
  controllers/administration.js
Labels: ready to merge

#2311 enable sorting on /files
  CHANGELOG.md
  locales/de.json
  locales/en.json
  static/scripts/files.js
  static/styles/files/files.scss
  views/files/files.hbs
Labels: auto update, waiting for UX review, waiting for review

#2337 SC-5179 - CKEditor on Task images selection
  CHANGELOG.md
  static/scripts/ckeditor/ckeditor.js
  views/homework/assignment.hbs
Labels: ready to merge

#2338 hotfix/SC-7803 - comments out failing tests for legacy lern store
  CHANGELOG.md
  package-lock.json
  package.json
  test/mocha/content/content.test.js
Labels: ready to merge

#2344 SC-7859 - class name is not required
  CHANGELOG.md
  views/administration/forms/form-classes-edit.hbs
Labels: auto update, ready to merge

#2348 Hotfix SC-7881 - restore external login fix
  CHANGELOG.md
  package-lock.json
  package.json
  static/scripts/login.js
Labels: ready to merge

#2346 Feature/SC-7845-github-action-changelog-fix
  .github/workflows/require_changelog.yml
  CHANGELOG.md
Labels: auto update, ready to merge

#2349 Hotfix/SC-1589 - Update error handling on team creation
  CHANGELOG.md
  controllers/teams.js
Labels: do_not_merge, waiting for review

#2254 Ce/remove console log
  CHANGELOG.md
  app.js
  config/default.schema.json
  controllers/alerts.js
  controllers/logs.js
  helpers/handlebars/helpers/index.js
  static/scripts/dropzone/dropzone.js
  static/scripts/topicEdit.js
  views/courses/create-course.hbs
  views/courses/edit-course.hbs
  views/lib/sentry.hbs
Labels: waiting for review

#2312 OPS-1508 - RAM and CPU Limit Docker Compse file
  CHANGELOG.md
  compose-client-test.dummy
Labels: auto update, waiting for review

#2356 SC-7842 - about page typo
  CHANGELOG.md
  views/about/about.hbs
Labels: auto update, ready to merge, waiting for review

#2353 SC-6119 - changed text for allOtherSchools on register
  CHANGELOG.md
  locales/de.json
  locales/en.json
  views/community/community.hbs
Labels: auto update, ready to merge

#2355 SC-5498 - fixed a source for shortTitle of instance
  CHANGELOG.md
  locales/de.json
  locales/en.json
  views/account/settings.hbs
  views/account/teams.hbs
Labels: auto update, ready to merge

#2352 SC-6825 - change collapsable icons
  CHANGELOG.md
  static/scripts/base.js
  views/authentication/forms/login.hbs
  views/help/partials/help_confluence_links.hbs
  views/homework/assignment.hbs
  views/homework/submissions.hbs
Labels: auto update, ready to merge

#2347 SC-7874 remove access to removed env values in global.js
  CHANGELOG.md
  app.js
Labels: auto update, ready to merge

#2360 SC-7771 - wrong hint for teachers on edit course
  CHANGELOG.md
  views/courses/create-course.hbs
  views/courses/edit-course.hbs
Labels: auto update, ready to merge

#2364 Feature/sc 5797 dashboard regular homeworks are shown for a teacher
  CHANGELOG.md
  views/dashboard/components/card_section.hbs
  views/dashboard/components/homework_tiles.hbs
  views/dashboard/dashboard.hbs
Labels: waiting for review

#2362 Change email addresses for tickets for niedersachcsen
  CHANGELOG.md
  controllers/helpdesk.js
  package-lock.json
  package.json
  theme/n21/views/help/mail-card.hbs
  theme/n21/views/help/partials/help_form_button_label_proper_team_name.hbs
  theme/n21/views/lib/extended_footer.hbs
  views/help/contact-card.hbs
  views/help/forms/form_bug.hbs
  views/help/forms/form_wish.hbs
  views/help/partials/help_form_button_label_proper_team_name.hbs
Labels: ready to merge

#2361 SC-7878 - dropdowns and multiselects
  CHANGELOG.md
  controllers/courses.js
  gulpfile.js
  package-lock.json
  package.json
  static/scripts/base.js
  static/scripts/chosen/chosen.jquery.min.js
  static/scripts/courses.js
  static/scripts/coursesTimes.js
  static/styles/courses/course.scss
  static/styles/files/files.scss
  views/authentication/forms/login.hbs
  views/content/forms/form-add-lesson.hbs
  views/courses/add-tool.hbs
  views/courses/components/template-new-course-time.hbs
  views/courses/components/topics.hbs
  views/courses/course.hbs
  views/courses/create-course.hbs
  views/courses/edit-course.hbs
  views/courses/edit-courseGroup.hbs
  views/courses/forms/form-tools.hbs
  views/files/files.hbs
  views/homework/edit.hbs
  views/lib/forms/form-date-input.hbs
  views/teams/forms/form-edit-member.hbs
  views/teams/forms/form-tools.hbs
Labels: waiting for UX review, waiting for review

#2366 SC-6825 - fix
  CHANGELOG.md
  views/authentication/forms/login.hbs
Labels: auto update, ready to merge

#2367 SC-7771 - wrong hint for teachers- fix
  CHANGELOG.md
  views/courses/edit-course.hbs
Labels: auto update, ready to merge

#2365 update commons location
  CHANGELOG.md
  app.js
  config/http-headers.js
  controllers/administration.js
  controllers/alerts.js
  controllers/firstLogin.js
  controllers/ghost.js
  controllers/index.js
  controllers/login.js
  controllers/oauth2.js
  controllers/registration.js
  controllers/rocketChat.js
  controllers/teams.js
  controllers/tools.js
  controllers/topics.js
  controllers/version.js
  helpers/apiHelper.js
  helpers/authentication.js
  helpers/cookieHelper.js
  helpers/handlebars/helpers/index.js
  helpers/handlebars/middleware.js
  helpers/i18n.js
  helpers/logger.js
  helpers/timesHelper.js
  middleware/cors.js
  middleware/security_headers.js
  package-lock.json
  package.json
  test/mocha/content/content.test.js
  test/mocha/helpers/i18n.test.js
Labels: ready to merge

#2370 SC-7983 - fixed that topic is now choosable after select of course
  CHANGELOG.md
  locales/de.json
  locales/en.json
  views/homework/edit.hbs
Labels: auto update, ready to merge
