Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2020-04, with the labels that each got.

#1721 Feature/sc 3732 homework fixes
  CHANGELOG.md
  controllers/homework.js
  static/scripts/homework.js
  static/styles/homework/discussions.scss
  views/homework/assignment.hbs
  views/homework/discussion.hbs
  views/homework/extended.hbs
Labels: ready to merge

#1723 Feature/reduce build time
  .dockerignore
Labels: ready to merge

#1722 SC-3868 - update nbc e-mail address
  CHANGELOG.md
  theme/n21/views/help/mail-card.hbs
  theme/n21/views/lib/extended_footer.hbs
Labels: ready to merge

#1725 update dataprivacy text
  CHANGELOG.md
  theme/brb/views/dataprivacy/text_einwilligung-dv.hbs
  theme/brb/views/dataprivacy/text_intro.hbs
  theme/open/views/dataprivacy/text_intro.hbs
  theme/thr/views/dataprivacy/privacy.hbs
  theme/thr/views/dataprivacy/text_intro.hbs
  views/dataprivacy/text_einwilligung-dv.hbs
  views/dataprivacy/text_intro.hbs
Labels: ready to merge

#1726 Homeworks Archive Quick Wins
  CHANGELOG.md
  controllers/courses.js
  controllers/dashboard.js
  helpers/handlebars/helpers/index.js
  locales/de.json
  static/styles/courses/course.scss
  static/styles/homework/assignment.scss
  static/styles/homework/homework.scss
  views/courses/components/tasks.hbs
  views/courses/course.hbs
  views/courses/overview.hbs
  views/homework/assignment.hbs
  views/homework/components/overview_card_template.hbs
  views/homework/edit.hbs
  views/homework/extended.hbs
  views/homework/feedback.hbs
Labels: ready to merge, waiting for review

#1729 [Hotfix] SC-3884 | update text on community page
  CHANGELOG.md
  package-lock.json
  package.json
  views/community/community.hbs
Labels: waiting for review

#1730 [HOTFIX] SC-3900 | Update tsc email on community page
  CHANGELOG.md
  package-lock.json
  package.json
  views/community/community.hbs
Labels: waiting for review

#1727 SC-3785 link to course after course creation corrected
  CHANGELOG.md
  views/courses/create-course.hbs
Labels: ready to merge

#1731 SC-3749 remove cookie domain
  .eslintrc.json
  CHANGELOG.md
  config/default.schema.json
  config/development.json
  config/global.js
  controllers/registration.js
  helpers/apiHelper.js
  helpers/authentication.js
  package-lock.json
  package.json
Labels: ready to merge

#1693 Feature/embedded messenger
  .github/workflows/security-audit.yml
  README.md
  config/default.schema.json
  controllers/index.js
  controllers/messenger.js
  static/indexeddb-worker.js
  static/riot_config.json
  static/scripts/chatLoggedin.js
  static/scripts/chatLoggedout.js
  static/styles/lib/chatLoggedin.scss
  static/styles/lib/colors.scss
  static/styles/lib/loggedin.scss
  views/lib/loggedin.hbs
  views/lib/loggedout.hbs
  views/lib/simple.hbs
Labels: ready to merge

#1733 SC-3560 localize /addons
  controllers/addons.js
  locales/de.json
  views/addons/addons.hbs
Labels: ready to merge

#1735 finished implementation for /dashboard
  controllers/dashboard.js
  locales/de.json
  views/dashboard/dashboard.hbs
Labels: ready to merge

#1736 SC-3560 - fix localization keys on homework/edit
  locales/de.json
  views/homework/edit.hbs
Labels: ready to merge

#1734 SC-3560 localize /courses/*
  controllers/coursegroups.js
  controllers/courses.js
  controllers/tools.js
  locales/de.json
  static/scripts/courses.js
  static/scripts/coursesOverview.js
  static/scripts/tools.js
  static/scripts/topic.js
  views/courses/components/topics.hbs
  views/courses/forms/form-import-course.hbs
  views/courses/forms/form-import-topic.hbs
  views/courses/forms/form-invitation.hbs
  views/courses/forms/form-tools.hbs
Labels: ready to merge

#1717 [SC-3719] Clean up shared files query and filter
  CHANGELOG.md
  controllers/files.js
  static/images/methodenguide.png
Labels: ready to merge

#1632 SC-3511 SC-3509 some small footer fixes
  theme/brb/views/lib/extended_footer.hbs
  theme/brb/views/lib/footer.hbs
  theme/open/views/lib/footer.hbs
  theme/thr/views/lib/extended_footer.hbs
  theme/thr/views/lib/footer.hbs
  views/lib/extended_footer.hbs
  views/lib/footer.hbs
Labels: ready to merge

#1741 Typo Fix
  locales/de.json
Labels: ready to merge

#1743 Fix: Messenger handle failed messenger token
  controllers/messenger.js
Labels: ready to merge

#1754 fix(messenger): change chat window based on course url
  static/scripts/chatLoggedin.js
  static/styles/lib/chatLoggedin.scss
Labels: ready to merge

#1742 Feature/sc 3560 authentication
  helpers/authentication.js
  locales/de.json
  static/scripts/login.js
  views/authentication/blog-card.hbs
  views/authentication/forms/demo-login.hbs
  views/authentication/forms/login.hbs
  views/authentication/forms/pwrecovery.hbs
  views/authentication/home.hbs
  views/courses/course.hbs
  views/courses/courseGroup.hbs
Labels: ready to merge

#1745 Fix: adjust eslint config to match CI
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ready to merge

#1759 hs/fix contact details in BRB
  theme/brb/views/help/people.hbs
Labels: ready to merge

#1747 SC-3757 add link to ldap docs
  CHANGELOG.md
  views/administration/forms/form-ldap-edit.hbs
  views/administration/ldap-edit.hbs
Labels: ready to merge

#1762 Dependency/updates
  package-lock.json
  package.json
Labels: ready to merge

#1773 SC438 - clear localStorage
  CHANGELOG.md
  views/lib/loggedin.hbs
Labels: ready to merge

#1764 SC-3611: messenger improvements
  config/default.schema.json
  locales/de.json
  static/scripts/chatLoggedin.js
  static/styles/lib/chatLoggedin.scss
  static/styles/lib/loggedin.scss
  views/courses/edit-course.hbs
  views/lib/loggedin.hbs
  views/teams/edit-team.hbs
Labels: ready to merge

#1753 add section for submissions
  CHANGELOG.md
  controllers/courses.js
  locales/de.json
  static/styles/courses/course.scss
  views/courses/components/tasks.hbs
  views/courses/course.hbs
  views/homework/components/course_overview_card_template.hbs
Labels: ready to merge

#1755 Feature/sc 3560/3936 courses
  controllers/courses.js
  helpers/handlebars/helpers/index.js
  locales/de.json
  views/courses/components/tools.hbs
  views/courses/components/topics.hbs
  views/courses/create-course.hbs
  views/courses/edit-course.hbs
  views/courses/forms/form-add-bbb-tool.hbs
  views/courses/forms/form-tools.hbs
  views/courses/overview-empty.hbs
  views/courses/overview.hbs
Labels: ready to merge

#1781 WIP fix jira issue SC-3990
  CHANGELOG.md
  controllers/administration.js
  controllers/registration.js
  helpers/authentication.js
  static/other/wordlist.js
  static/scripts/dataprivacy/user-registration.js
  views/administration/users_skipregistration.hbs
  views/registration/registration-parent.hbs
  views/registration/registration-student.hbs
Labels: ready to merge

#1757 Feature/sc 3560 authentication
  locales/de.json
  static/scripts/loggedin.js
  static/scripts/login.js
  views/authentication/forms/pwrecovery.hbs
  views/authentication/home.hbs
Labels: ready to merge

#1787 Hotfix/22.9.10
  package-lock.json
  package.json
  theme/brb/views/authentication/home.hbs
  views/authentication/home.hbs
Labels: do_not_merge

#1775 SC 3935: Merge different matrix messenger feature flags
  app.js
  config/global.js
  views/administration/school.hbs
  views/courses/edit-course.hbs
  views/teams/edit-team.hbs
Labels: ready to merge

#1778 SC-3577: add school feature flag to add messenger room for whole school
  config/default.schema.json
  controllers/administration.js
  static/scripts/administration/school.js
  static/scripts/chatLoggedin.js
  static/styles/lib/chatLoggedin.scss
  views/administration/school.hbs
Labels: ready to merge
