Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2020-03, with the labels that each got.

#1619 SC-3182 Hide email verification page for generated emails
  controllers/firstLogin.js
Labels: ready to merge

#1624 Update tutorials.json
  helpers/content/tutorials.json
Labels: waiting for review

#1625 Update Sebastian's profile image
  static/images/team/Sebastian_Serth.jpg
Labels: ready to merge

#1587 SC-1013-invitation-click-behavior
  controllers/teams.js
  static/scripts/teamOverview.js
Labels: ready to merge

#1629 create npm audit workflow
  .github/workflows/security-audit.yml
Labels: ready to merge

#1630 update warning about inline homeworks
  static/scripts/topicEdit.js
Labels: LOKI, ready to merge

#1634 feature/SC-3560 i18n setup
  app.js
  controllers/dashboard.js
  helpers/handlebars/helpers/index.js
  helpers/handlebars/middleware.js
  helpers/i18n.js
  locale/de.json
  locale/en.json
  locales/de.json
  locales/en.json
  middleware/i18n.js
  nodemon.json
  package-lock.json
  package.json
  static/scripts/i18n.js
  views/dashboard/components/card_section.hbs
  views/dashboard/dashboard.hbs
  views/lib/default.hbs
Labels: ready to merge

#1635 fixed empty state
  views/courses/overview-empty.hbs
Labels: ready to merge

#1636 Changed text on link
  views/help/lern-nuggets.hbs
Labels: ready to merge

#1638 Update Pilotschulen Bosscloud
  helpers/content/schools.json
Labels: ready to merge

#1642 Fotos der HPI Schul-Cloud-Team update
  helpers/content/team.js
  static/images/team/Christian_Weissmann.jpg
  static/images/team/Christiane_Hagedorn.jpg
  static/images/team/Christina_Anders.jpg
  static/images/team/Florian_Morel.jpg
  static/images/team/Julian_Taraz.png
  static/images/team/Karolina_K.jpg
  static/images/team/Martin_Malchow.jpg
  static/images/team/Marvin_Fischer.jpg
  static/images/team/Matthias_Wiesner.jpg
  static/images/team/Max_Bothe.jpg
  static/images/team/Michael_Schmid.jpg
  static/images/team/Mona.png
  static/images/team/Nils_Karn.jpg
  static/images/team/Robert_Weber.jpg
  static/images/team/Sophie_Krueger.jpg
  static/images/team/Thomas_Feldtkeller.jpg
  static/images/team/josefine_fogain.jpg
  static/images/team/luisa_schrott.jpg
  static/images/team/luisa_schrott.png
  static/images/team/prisca_menz.jpg
  static/images/team/ramona_weitzenberg.jpg
  static/images/team/sarah_schaefer.jpg
  static/images/team/sophie_krueger.jpg
  static/images/team/tatiana.jpg
  static/images/team/thomas_feldtkeller.jpg
  static/images/team/tormod.png
  static/images/team/tormod_flesjo.jpg
Labels: ready to merge

#1649 Hotfix/22.3.1
  helpers/csrf.js
  package-lock.json
  package.json
  views/lib/csrf_content.hbs
Labels: do_not_merge

#1650 update browserlist supported ranges
  gulpfile.js
  static/scripts/base.js
  static/scripts/dataprivacy/pin_input.js
  static/scripts/helpers/inputFromQuery.js
Labels: waiting for review

#1651 SC-2842 - file sort
  .eslintrc.json
  controllers/files.js
  static/scripts/files.js
  views/files/files.hbs
Labels: ready to merge, waiting for review

#1662 Feature/sc 3560 text to var
  .eslintrc.json
  locales/de.json
  static/scripts/partners.js
  theme/brb/views/lib/default.hbs
  theme/open/views/lib/default.hbs
  theme/thr/views/lib/default.hbs
  views/about/about.hbs
  views/courses/add-tool.hbs
  views/courses/course.hbs
  views/courses/courseGroup.hbs
Labels: ready to merge

#1661 SC-3162 | fixed design and branding issues in fristLogin
  static/images/firstLogin/welcome-banner.svg
  static/images/firstLogin/welcome_screen.svg
  static/styles/firstLogin/thanks.scss
  views/firstLogin/sections/thanks.hbs
Labels: LOKI, ready to merge

#1667 Progress on /courses
  locales/de.json
  views/courses/create-course.hbs
  views/courses/edit-course.hbs
Labels: ready to merge

#1631 ce/ stable and performance fix for show course
  controllers/courses.js
Labels: LOKI, waiting for review

#1672 SC-3673 remove google analytics
  README.md
  compose-client-test.dummy
  controllers/index.js
  helpers/googleAnalytics.js
  package-lock.json
  package.json
Labels: ready to merge

#1682 SC-3689 replace the current contact email address
  config/default.schema.json
  theme/open/views/imprint/imprint.hbs
  theme/thr/views/imprint/imprint.hbs
  theme/thr/views/lib/footer.hbs
  views/community/community.hbs
  views/imprint/imprint_rights.hbs
  views/lib/extended_footer_links.hbs
  views/lib/footer.hbs
Labels: ready to merge

#1665 moved import to a new page
  controllers/administration.js
  static/scripts/administration.js
  views/administration/forms/form-import.hbs
  views/administration/import.hbs
  views/administration/students.hbs
  views/administration/teachers.hbs
Labels: ready to merge

#1645 Änderungen Team-Seite
  helpers/content/team.js
Labels: ready to merge

#1687 SC-3707 added robots to disallow long links and link and registration resolver
  static/robots.txt
Labels: ready to merge

#1684 Feature/SC-2997/remove process env from callbacks
  config/consent.js
  config/documents.js
  config/global.js
  config/http-headers.js
  controllers/account.js
  controllers/administration.js
  controllers/courses.js
  controllers/files.js
  controllers/firstLogin.js
  controllers/homework.js
  controllers/link.js
  controllers/notification.js
  controllers/registration.js
  controllers/rocketChat.js
  controllers/teams.js
  controllers/topics.js
  controllers/version.js
  controllers/videoconference.js
  helpers/authentication.js
  helpers/handlebars/helpers/index.js
  helpers/handlebars/middleware.js
  helpers/logger.js
  helpers/theme.js
  middleware/cors.js
  middleware/security_headers.js
  package-lock.json
  test/mocha/helper/login-helper.js
  test/mocha/link/link.test.js
Labels: ready to merge

#1660 now shows only 4 schools
  controllers/about.js
Labels: ready to merge

#1699 SC-1594 add graphics in empty state dashboard
  locales/de.json
  locales/en.json
  static/images/empty-states/emptystate-graph.svg
  static/images/empty-states/news-empty.svg
  static/images/empty-states/tasks-empty.svg
  static/images/empty-states/timetable-empty.svg
  static/styles/dashboard/dashboard.scss
  views/dashboard/dashboard.hbs
Labels: ready to merge

#1698 [Hotfix] SC-3773 | readded demo login
  package-lock.json
  package.json
  views/authentication/home.hbs
Labels: ready to merge

#1490 SC-2447 | Added EBS (Alert) System
  config/default.schema.json
  controllers/alerts.js
  controllers/index.js
  static/scripts/alerts.js
  static/scripts/helpers/AlertMessageController.js
  static/scripts/loggedin.js
  static/scripts/login.js
  static/styles/lib/loggedin.scss
  views/authentication/forms/login.hbs
  views/lib/loggedin.hbs
Labels: ready to merge

#1694 add changelog to project
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
Labels: ready to merge

#1637 feature/SC-3028-use EDITOR_URL
  config/global.js
  controllers/topics.js
  views/topic/topic-edtr.hbs
Labels: ready to merge

#1686 add api catch handler
  controllers/about.js
  controllers/calendar.js
  controllers/community.js
  controllers/content.js
  controllers/coursegroups.js
  controllers/dashboard.js
  controllers/dataprivacy.js
  controllers/files.js
  controllers/users.js
  controllers/videoconference.js
Labels: ready to merge

#1680 Feature/sc 3560 text to var
  locales/de.json
  locales/en.json
  views/administration/users_edit.hbs
  views/administration/users_registrationcomplete.hbs
  views/administration/users_skipregistration.hbs
  views/calendar/calendar.hbs
  views/calendar/card.hbs
  views/calendar/forms/form-create-event.hbs
  views/content/forms/form-add-lesson.hbs
  views/courses/add-tool.hbs
  views/courses/components/groups.hbs
  views/courses/components/tasks.hbs
  views/courses/components/template-new-course-time.hbs
  views/courses/components/tools.hbs
  views/courses/components/topics.hbs
  views/courses/course.hbs
  views/courses/courseGroup.hbs
  views/courses/create-course.hbs
  views/courses/edit-course.hbs
  views/courses/edit-courseGroup.hbs
  views/courses/overview-empty.hbs
  views/courses/overview.hbs
  views/courses/run-lti.hbs
  views/courses/run-tool-local.hbs
  views/files/file-upload.hbs
  views/files/file-viewer.hbs
  views/files/files-grid.hbs
  views/files/files.hbs
  views/files/forms/form-move.hbs
  views/files/forms/form-name-edit.hbs
  views/files/forms/form-new-file.hbs
  views/files/forms/form-share-file.hbs
  views/files/forms/form-virus-danger.hbs
  views/files/lool.hbs
  views/files/search.hbs
  views/firstLogin/sections/thanks.hbs
  views/homework/assignment.hbs
  views/homework/components/course_overview_card_template.hbs
  views/homework/components/overview_card_template.hbs
  views/homework/components/submission_uploaded_files.hbs
  views/homework/edit.hbs
  views/homework/evaluation.hbs
  views/homework/extended.hbs
  views/homework/feedback.hbs
  views/homework/overview.hbs
  views/homework/submission.hbs
  views/news/article.hbs
  views/news/edit.hbs
  views/news/overview.hbs
Labels: ready to merge

#1701 [PROPOSAL] Display Env variables at server start in an ordered list
  config/global.js
Labels: ready to merge

#1646 SC-3574 | Add chat option to course
  app.js
  config/global.js
  controllers/administration.js
  controllers/courses.js
  controllers/teams.js
  views/administration/school.hbs
  views/courses/edit-course.hbs
  views/teams/edit-team.hbs
Labels: LOKI, ready to merge

#1714 Homework speichern label umbenannt
  locales/de.json
Labels: ready to merge

#1712 Feature/sc 3791 dashboard rework homeschooling
  controllers/dashboard.js
  locales/de.json
  static/styles/courses/course.scss
  static/styles/dashboard/dashboard.scss
  views/dashboard/components/card_section.hbs
  views/dashboard/components/homework_tiles.hbs
  views/dashboard/dashboard.hbs
  views/homework/edit.hbs
Labels: ready to merge

#1718 [FOLLOWUP] SC-3791 |added demo support; timetable placeholder update
  controllers/dashboard.js
  static/images/empty-states/timetable-empty-bg.svg
  static/images/empty-states/timetable-empty-cards.svg
  static/images/empty-states/timetable-empty.svg
  static/styles/dashboard/dashboard.scss
  views/dashboard/dashboard.hbs
Labels: ready to merge

#1719 SC-3816 | fixed typo in filter
  controllers/homework.js
Labels: ready to merge

#1720 SC Client now renders bold/italics for PT Sans
  CHANGELOG.md
  static/fonts/ptsans/_ptsans.css
  static/fonts/ptsans/ptsans-bold-italic.woff2
  static/fonts/ptsans/ptsans-bold.woff2
  static/fonts/ptsans/ptsans-italic.woff2
  static/fonts/ptsans/ptsans-regular.woff2
  static/fonts/ptsans/ptsans.css
  theme/brb/views/lib/default.hbs
  theme/open/views/lib/default.hbs
  theme/thr/views/lib/default.hbs
  views/lib/default.hbs
  views/oauth2/username.hbs
Labels: ready to merge
