Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2020-02, with the labels that each got.

#1598 Tf/fix homework archiving
  controllers/homework.js
Labels: waiting for review

#1571 Sc 2408 bbb
  config/default.schema.json
  controllers/administration.js
  controllers/calendar.js
  controllers/courses.js
  controllers/index.js
  controllers/teams.js
  controllers/videoconference.js
  gulpfile.js
  static/images/tools/bbb/available.png
  static/images/tools/bbb/no_permission.png
  static/images/tools/bbb/not_started.png
  static/scripts/calendar.js
  static/scripts/courses.js
  static/scripts/tabbar.js
  static/scripts/teams.js
  static/scripts/tools.js
  static/scripts/videoconference.js
  static/styles/calendar/calendar.scss
  static/styles/courses/course.scss
  static/styles/teams/teams.scss
  static/styles/tools/tools.scss
  theme/n21/static/other/pdf/bbb-default-presentation.pdf
  views/administration/school.hbs
  views/calendar/card.hbs
  views/calendar/forms/form-create-event.hbs
  views/courses/add-tool.hbs
  views/courses/components/tools.hbs
  views/courses/course.hbs
  views/courses/forms/form-add-bbb-tool.hbs
  views/lib/forms/form-bbb-forbidden-info.hbs
  views/lib/forms/form-bbb-reload-info.hbs
  views/lib/forms/form-create-videoconference.hbs
  views/teams/edit-team.hbs
  views/teams/team.hbs
  webpack.config.js
Labels: IntegraTHORs

#1605 moved integration-test script from gist into repo
  .travis.yml
Labels: ready to merge

#1603 SC-2590 SC-2592 SC-2593 SC-2594
  helpers/theme.js
  theme/brb/views/dataprivacy/privacy.hbs
  theme/brb/views/dataprivacy/privacy_anschrift.hbs
  theme/brb/views/dataprivacy/privacy_cookies.hbs
  theme/brb/views/dataprivacy/privacy_erh-persb-daten.hbs
  theme/brb/views/dataprivacy/privacy_logged_in.hbs
  theme/brb/views/dataprivacy/text_einwilligung-dv.hbs
  theme/brb/views/dataprivacy/text_intro.hbs
  theme/open/views/dataprivacy/privacy.hbs
  theme/open/views/dataprivacy/privacy_anschrift.hbs
  theme/open/views/dataprivacy/privacy_cookies.hbs
  theme/open/views/dataprivacy/privacy_erh-persb-daten.hbs
  theme/open/views/dataprivacy/privacy_tom.hbs
  theme/open/views/dataprivacy/privacy_weiterg-von-daten.hbs
  theme/open/views/dataprivacy/text_datenverarbeitung-schulen.hbs
  theme/open/views/dataprivacy/text_intro.hbs
  theme/open/views/dataprivacy/text_rechte.hbs
  theme/thr/views/dataprivacy/privacy.hbs
  theme/thr/views/dataprivacy/text_intro.hbs
  views/dataprivacy/privacy.hbs
  views/dataprivacy/privacy_anschrift.hbs
  views/dataprivacy/privacy_cookies.hbs
  views/dataprivacy/privacy_erh-persb-daten.hbs
  views/dataprivacy/privacy_logs.hbs
  views/dataprivacy/privacy_newsletter.hbs
  views/dataprivacy/privacy_priv-und-daten.hbs
  views/dataprivacy/privacy_rechte.hbs
  views/dataprivacy/privacy_self-audit.hbs
  views/dataprivacy/privacy_tom.hbs
  views/dataprivacy/privacy_verantw-stelle.hbs
  views/dataprivacy/privacy_verarb-persb-daten.hbs
  views/dataprivacy/privacy_webanalyse.hbs
  views/dataprivacy/privacy_weiterg-von-daten.hbs
  views/dataprivacy/text_chat.hbs
  views/dataprivacy/text_datensicherheit.hbs
  views/dataprivacy/text_datenverarbeitung-schulen.hbs
  views/dataprivacy/text_datenverarbeitung-web.hbs
  views/dataprivacy/text_einwilligung-dv.hbs
  views/dataprivacy/text_helpdesk.hbs
  views/dataprivacy/text_intro.hbs
  views/dataprivacy/text_persbezogene-daten.hbs
  views/dataprivacy/text_rechte.hbs
  views/dataprivacy/text_speicherdauer.hbs
  views/dataprivacy/text_weitergabe-von-daten.hbs
Labels: ready to merge

#1568 SC-2100 Latex Formeln werden nicht richtig dargestellt
  static/scripts/homework.js
  views/homework/components/course_overview_card_template.hbs
Labels: ready to merge

#1616 Feature/sc 3232 editor closed beta unlock
  controllers/courses.js
  views/courses/components/topics.hbs
Labels: ready to merge

#1593 SC-1115-homework-overview-math
  static/scripts/homework.js
Labels: ready to merge

#1618 Update dependencies
  Dockerfile
  gulpfile.js
  package-lock.json
  package.json
Labels: ready to merge

#1620 Fix link to web dev job offer
  theme/open/views/authentication/home.hbs
  theme/thr/views/lib/extended_footer.hbs
  views/community/community.hbs
  views/lib/extended_footer.hbs
Labels: ready to merge

#1595 Changed order of navigation
  views/lib/header.hbs
Labels: ready to merge

#1609 SC-2074 - fix wrong data priv documents in BRB
  theme/brb/views/lib/extended_footer.hbs
Labels: ready to merge

#1622 Add boolean helper, add toogle in topic patch route, linter.
  controllers/courses.js
  controllers/topics.js
  package-lock.json
Labels: ready to merge

#1623 feature/make repo compatible with node 12
  .gitmodules
  .nvmrc
  .travis.yml
  Dockerfile
  Dockerfile.brb
  Dockerfile.n21
  Dockerfile.open
  Dockerfile.thr
  package-lock.json
  package.json
Labels: ready to merge
