Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2020-05, with the labels that each got.

#1802 Fix typo in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready to merge

#1797 SC-3577: disable messenger option if user lacks edit permissions
  views/administration/school.hbs
Labels: ready to merge

#1809 Update README.md
  README.md
Labels: ready to merge

#1771 SC-3945 - unarchive courses
  CHANGELOG.md
  controllers/courses.js
  locales/de.json
Labels: ready to merge

#1812 hs/rename Lern-Nuggets
  controllers/help.js
  views/help/partials/help_nutzungshilfen.hbs
Labels: ready to merge

#1807 SC-4190 - Route for fetching blogs RSS data
  controllers/blog.js
  controllers/index.js
  controllers/login.js
  views/authentication/home.hbs
Labels: ready to merge

#1769 SC-4260 (former Hotfix/22.9.8) enable sentry sample rate
  CHANGELOG.md
  app.js
  config/default.schema.json
  config/global.js
  static/vendor/ckeditor/styles.js
  views/lib/sentry.hbs
Labels: ready to merge

#1798 Feature/sc 4066 footer text change
  theme/brb/views/lib/extended_footer.hbs
  theme/brb/views/lib/footer.hbs
  theme/open/views/lib/extended_footer.hbs
  theme/open/views/lib/footer.hbs
  theme/thr/views/lib/extended_footer.hbs
  theme/thr/views/lib/footer.hbs
  views/lib/extended_footer.hbs
  views/lib/footer.hbs
Labels: ready to merge

#1770 feature / sc-3560-topic
  locales/de.json
  views/topic/components/content-Etherpad.hbs
  views/topic/components/content-internal.hbs
  views/topic/components/content-neXboard.hbs
  views/topic/edit-topic.hbs
  views/topic/forms/form-share.hbs
  views/topic/topic.hbs
Labels: ready to merge

#1789 SC-4037 Landing Page "Registrieren" Link + New Registrieren Page
  controllers/community.js
  locales/de.json
  static/images/community.svg
  static/images/logo/brb-schoolcloud-logo.svg
  static/images/logo/globe.svg
  static/images/logo/hand-in-hand.svg
  static/images/logo/n21-schoolcloud-logo.svg
  static/images/logo/th-schoolcloud-logo.svg
  static/styles/about/about.scss
  static/styles/community/community.scss
  static/styles/homepage/index.scss
  views/community/community.hbs
  views/community/community_guest.hbs
  views/community/community_loggedin.hbs
  views/lib/header.hbs
Labels: ready to merge

#1779 hs/Add datetime question to contact mails
  static/scripts/helpers/form_bug_text.js
Labels: ready to merge

#1758 Feature/sc 3560 pw recovery
  locales/de.json
  static/scripts/pwrecovery.js
  views/lib/forms/password-hint.hbs
  views/lib/header.hbs
  views/pwRecovery/pwRecoveryResponse.hbs
  views/pwRecovery/pwrecovery.hbs
Labels: ready to merge

#1818 SC-3572: Messenger Improvments
  config/default.schema.json
  static/styles/lib/chatLoggedin.scss
Labels: waiting for UX review, waiting for review

#1823 SC-4328: add flag to hide school messenger settings
  config/default.schema.json
  views/administration/school.hbs
  views/courses/edit-course.hbs
  views/teams/edit-team.hbs
Labels: waiting for review

#1793 SC-3560 translating /oauth2
  controllers/oauth2.js
  locales/de.json
  views/account/settings.hbs
  views/oauth2/consent.hbs
Labels: ready to merge

#1783 [#SC-4064] Allow bulk download of ungraded homework files (2/4)
  CHANGELOG.md
  controllers/homework.js
  locales/de.json
  locales/en.json
  package-lock.json
  package.json
  static/scripts/homework.js
  views/homework/submissions.hbs
Labels: ready to merge

#1821 SC-4191 - Fetch blogs on the client side
  locales/de.json
  static/scripts/blog-fetch.js
  views/authentication/home.hbs
Labels: ready to merge

#1816 Prevent logging in as a Superhero
  config/default.schema.json
  config/global.js
  controllers/login.js
  helpers/authentication.js
  locales/de.json
  locales/en.json
  test/mocha/helper/login-helper.js
  test/mocha/login/superheroLogin.test.js
Labels: ready to merge

#1808 [#SC-3949] Fixed issue with displaying team members
  controllers/administration.js
  static/scripts/administration/teams.js
  static/styles/lib/bootstrap/scss/_modal.scss
Labels: ready to merge

#1824 SC-4111 - Bcrypt Passwortlange
  views/authentication/forms/login.hbs
Labels: ready to merge

#1819 feature/SC-4075-TeamCreationPermissions
  CHANGELOG.md
  config/default.json
  config/default.schema.json
  controllers/administration.js
  controllers/teams.js
  views/administration/teams.hbs
Labels: blocked_by_server_pr, waiting for UX review

#1838 Feature/SC-4252-about-page-in-ghost
  static/scripts/about-ghost.js
  views/about/about.hbs
  views/about/about_guest.hbs
  views/about/about_loggedin.hbs
Labels: waiting for review

#1830 SC-3614: automatically load newest messenger version
  config/default.schema.json
  static/indexeddb-worker.js
  static/riot_config.json
  static/scripts/chatLoggedin.js
  static/styles/lib/chatLoggedin.scss
  views/lib/loggedin.hbs
Labels: ready to merge

#1786 Sc 4093 homework status icon
  controllers/homework.js
  locales/de.json
  static/styles/homework/assignment.scss
  static/styles/homework/homework.scss
  views/homework/assignment.hbs
  views/homework/components/overview_card_template.hbs
Labels: ready to merge

#1827 [#SC-3887] fixed double submit
  views/homework/submission.hbs
Labels: ready to merge
