Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2020-06, with the labels that each got.

#1857 SC-4550: allow to specify restrictive copy patterns for vendor files
  gulpfile.js
Labels: ready to merge

#1870 sc-4487 removing firebase notifications.
  static/scripts/loggedin.js
  static/scripts/notificationService/callback.js
  static/scripts/notificationService/firebase-messaging-sw.js
  static/scripts/notificationService/index.js
  static/scripts/notificationService/indexFirebase.js
  static/scripts/notificationService/indexSafari.js
  static/scripts/settings.js
Labels: ready to merge

#1859 Feature/SC-3942 pagination teams page
  controllers/administration.js
  test/mocha/homework/homework.test.js
  views/administration/teams.hbs
Labels: ready to merge

#1875 Feature/sc-4555-new-footer-link
  controllers/index.js
  controllers/security.js
  static/styles/security/security.scss
  views/lib/extended_footer.hbs
  views/lib/footer.hbs
  views/security/security.hbs
  views/security/security_guests.hbs
  views/security/security_loggedin.hbs
Labels: ready to merge

#1888 [SC-4760] Removed title
  controllers/team.js
  views/team/team.hbs
Labels: ready to merge

#1792 feature/SC-4056/timetable check for events
  controllers/dashboard.js
  locales/de.json
  locales/en.json
  views/dashboard/dashboard.hbs
Labels: ready to merge, waiting for UX review

#1883 SC-4607 - Update /datenschutz links for all instances (except NBC)
  config/documents.js
  controllers/dataprivacy.js
Labels: ready to merge

#1832 i18n SC-4707 my_material && template
  locales/de.json
  static/images/chrome.png
  static/images/login-fail.png
  static/images/safari.png
  static/images/thr-logo.png
  views/my-material/my-material.hbs
  views/template/registration.hbs
Labels: i18n, ready to merge

#1831 i18n SC-4706 LernStore
  locales/de.json
  views/content/forms/form-add-lesson.hbs
  views/content/forms/form-external-link.hbs
  views/content/item.hbs
  views/content/store.hbs
Labels: i18n, ready to merge

#1845 Show hint for safari users to open tool in new tab
  static/scripts/tools.js
  static/styles/courses/course.scss
  static/styles/tools/tools.scss
  views/courses/add-tool.hbs
  views/courses/components/tools.hbs
  views/courses/run-tool-local.hbs
  views/teams/topics.hbs
Labels: waiting for UX review

#1884 SC - 4713-registration-page-error-hash
  static/scripts/dataprivacy/registration-link-validation.js
  static/styles/administration/dataprivacy.scss
Labels: ready to merge

#1895 [SC-4655] Removed html tags from json
  locales/de.json
  views/lib/forms/password-hint.hbs
Labels: waiting for review

#1903 SC-4764 add file to graded submission
  controllers/homework.js
  package-lock.json
  package.json
Labels: waiting for review

#1897 commented deletion of borders out; does it have any sideeffects?
  static/vendor/ckeditor/config.js
Labels: ready to merge

#1890 SC-4715 - timeout-on-registration
  controllers/registration.js
  views/registration/registration.hbs
Labels: waiting for review

#1906 i18n SC-4905 rework files
  locales/de.json
  views/files/file-viewer.hbs
  views/files/files-grid.hbs
  views/files/files.hbs
  views/files/forms/form-file-permissions.hbs
  views/files/forms/form-new-file.hbs
  views/files/search.hbs
Labels: i18n, ready to merge

#1915 Feature/sc 4741 navbar client
  controllers/community.js
  controllers/login.js
  static/styles/about/about.scss
  static/styles/homepage/header.scss
  static/styles/homepage/index.scss
  views/lib/header.hbs
Labels: waiting for review

#1914 Login Failed, wording fixes
  locales/de.json
Labels: ready to merge

#1932 Hotfix/23.4.3 SC-5048 disable portfolio
  CHANGELOG.md
  config/default.json
  config/default.schema.json
  controllers/tools.js
  locales/de.json
  package-lock.json
  package.json
  theme/n21/views/addons/addons.hbs
  views/addons/addons.hbs
Labels: waiting for review

#1940 deleted duplicate
  views/lib/header.hbs
Labels: waiting for review

#1919 feature/SC-4580-fix-menu-items
  app.js
Labels: waiting for review

#1767 i18n SC-4698 Translation Teams
  controllers/teams.js
  locales/de.json
  static/scripts/teams.js
  views/help/partials/help_form_invite_external_members.hbs
  views/teams/edit-team.hbs
  views/teams/forms/form-add-member.hbs
  views/teams/forms/form-delete-class.hbs
  views/teams/forms/form-delete-invitation.hbs
  views/teams/forms/form-delete-member.hbs
  views/teams/forms/form-edit-member.hbs
  views/teams/forms/form-file-permissions.hbs
  views/teams/forms/form-invitation.hbs
  views/teams/forms/form-invite-external-member.hbs
  views/teams/forms/form-leave-team.hbs
  views/teams/forms/form-resend-invitation.hbs
  views/teams/members.hbs
  views/teams/overview-empty.hbs
  views/teams/overview.hbs
  views/teams/team.hbs
Labels: i18n, ready to merge

#1898 OPS-456 move cookie secret to environment var
  app.js
  config/default.json
  config/default.schema.json
Labels: ready to merge

#1930 [SC-4909] old text replace
  views/firstLogin/partials/welcome_existing.hbs
Labels: waiting for review

#1953 SC-5197 Fixed missing file download for teams
  controllers/files.js
Labels: ready to merge

#1951 SC-5200 - landingpage-changes
  static/styles/homepage/index.scss
Labels: waiting for review

#1926 Feature/fix tool safari workaround
  config/http-headers.js
  views/courses/add-tool.hbs
  views/courses/run-tool-local.hbs
Labels: ready to merge

#1952 gitflow-hotfix-stash: 1/deploy_hotfix
  deploy.sh
Labels: do_not_merge

#1954 SC-5206 - change-button-name
  locales/de.json
Labels: waiting for review

#1941 teachers without permission: remove adding classes
  locales/de.json
  views/courses/create-course.hbs
Labels: waiting for review

#1959 i18n SC-5262 Bugfix: content sometimes loads before initialization
  static/scripts/i18n.js
Labels: i18n

#1957 SC-4694 - Generated passwords of manual consent not consistent
  config/global.js
  controllers/administration.js
  helpers/authentication.js
  package-lock.json
  package.json
  test/mocha/helpers/authentication.test.js
Labels: ready to merge

#1834 i18n SC-4372 Translation Partner Page
  controllers/partner.js
  locales/de.json
  views/partner/partner.hbs
Labels: i18n, ready to merge

#1933 SC-5173: i18n translating static scripts: news,csrf,help,settings
  locales/de.json
  static/scripts/csrf.js
  static/scripts/help.js
  static/scripts/news.js
  static/scripts/settings.js
Labels: i18n, ready to merge

#1960 [SC-4980] Hilfebereich as a menu point on the left side
  controllers/help.js
  helpers/handlebars/middleware.js
  locales/de.json
  static/styles/help/dashboard.scss
  static/styles/lib/loggedin.scss
  views/help/contact-card.hbs
  views/help/contact.hbs
  views/help/dashboard.hbs
  views/help/partials/help_contact.hbs
  views/lib/loggedin.hbs
Labels: ready to merge

#1972 Feature/SC-5327 remove bereich from navigation items
  CHANGELOG.md
  locales/de.json
Labels: ready to merge

#1945 i18n SC-5049 Translation Static Scripts dataprivacy
  locales/de.json
  static/scripts/dataprivacy/paginated_form.js
  static/scripts/dataprivacy/pin.js
  static/scripts/dataprivacy/registration-link-validation.js
  static/scripts/dataprivacy/user-registration.js
Labels: i18n, ready to merge

#1907 i18n SC-4906 Static Scripts Administration
  locales/de.json
  static/scripts/administration.js
  static/scripts/administration/classes/manage.js
  static/scripts/administration/school.js
  static/scripts/administration/systems/ldap-edit.js
  static/scripts/administration/teams.js
  static/scripts/administration/users_edit.js
Labels: i18n, ready to merge

#1811 i18n SC-4702 Translations javascripts
  controllers/calendar.js
  controllers/content.js
  controllers/coursegroups.js
  controllers/files.js
  helpers/handlebars/middleware.js
  locales/de.json
  static/scripts/calendar.js
  static/scripts/content.js
  static/scripts/files.js
  views/calendar/forms/form-create-event.hbs
  views/content/forms/form-external-link.hbs
  views/content/forms/form-search.hbs
  views/content/item.hbs
  views/content/store.hbs
Labels: i18n, ready to merge

#1974 Sc i18n static scripts team overview/members
  locales/de.json
  static/scripts/teamMembers.js
  static/scripts/teamOverview.js
Labels: i18n, ready to merge

#1967 Feature/SC-4515-Externe-Expert-button-activated
  locales/de.json
  package-lock.json
  theme/n21/views/help/partials/help_form_invite_external_members.hbs
Labels: ready to merge

#1877 add class for white links on red background
  static/styles/help/help.scss
  views/help/partials/help_confluence_links.hbs
Labels: ready to merge
