Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2020-07, with the labels that each got.

#1975 add testIds for integrations tests
  views/administration/classes.hbs
  views/administration/forms/form-classes-edit.hbs
Labels: ready to merge

#1973 add icon to top bar
  locales/de.json
  static/images/logo/fortbildung.svg
  views/lib/help_menu.hbs
Labels: ready to merge

#1925 SC-4520 - activation service
  controllers/account.js
  locales/de.json
  views/account/teams.hbs
  views/account/thirdPartyProviders.hbs
Labels: ready to merge

#1962 SC-3181: notification for matrix messenger
  app.js
  config/global.js
  controllers/teams.js
  locales/de.json
  views/lib/components/notification.hbs
  views/lib/loggedin.hbs
Labels: ready to merge

#1948 i18n SC-5199 Translation Static Scripts helpers
  locales/de.json
  static/scripts/help.js
  static/scripts/helpers/AlertMessageController.js
  static/scripts/helpers/form_bug_text.js
  static/scripts/helpers/navigation.js
  static/scripts/helpers/printQRs.js
Labels: i18n, ready to merge

#1873 small UI fixes on landing page
  static/styles/homepage/index.scss
Labels: ready to merge

#1965 Ys/sc 4995
  static/images/logo/fortbildung.svg
  views/courses/create-course.hbs
  views/courses/overview.hbs
  views/dashboard/components/card_section.hbs
  views/lib/components/sc-card.hbs
  views/lib/forms/paginatedForm.hbs
Labels: ready to merge

#1918 SC 4871: add content security policy settings for matrix messenger
  config/default.schema.json
  config/http-headers.js
Labels: ready to merge

#1949 i18n SC-5219 Translation Static Scripts base, dashboard
  locales/de.json
  static/scripts/base.js
  static/scripts/dashboard.js
  static/scripts/login.js
  static/scripts/teams.js
Labels: i18n, ready to merge

#1979 [SC-5401] Changed Hilfebereich on NBC
  config/default.schema.json
  config/global.js
  helpers/handlebars/middleware.js
  views/lib/loggedin.hbs
Labels: ready to merge

#1942 OPS-737 Fixed the filter logic on create trigger
  .github/workflows/update_version.yml
Labels: waiting for review

#1964 SC-4982 add explanation message below qr code
  locales/de.json
  locales/en.json
  static/styles/lib/loggedin.scss
  views/lib/loggedin.hbs
Labels: ready to merge

#1852 i18n SC-4711 Translation Helpers
  controllers/courses.js
  controllers/teams.js
  helpers/handlebars/helpers/index.js
  helpers/handlebars/middleware.js
  helpers/recurringEvents.js
  locales/de.json
  test/mocha/helper/recurringEvents.test.js
Labels: i18n, ready to merge

#1846 i18n SC-4709 Translation Controllers
  controllers/account.js
  controllers/courses.js
  controllers/dataprivacy.js
  controllers/firstLogin.js
  controllers/help.js
  controllers/helpdesk.js
  controllers/homework.js
  controllers/imprint.js
  controllers/link.js
  controllers/my-material.js
  controllers/news.js
  controllers/pwrecovery.js
  controllers/registration.js
  controllers/schools.js
  controllers/team.js
  controllers/teams.js
  controllers/topics.js
  controllers/users.js
  locales/de.json
  views/news/edit.hbs
Labels: i18n, ready to merge

#1987 Feature/SC-3999 fixing title teacher import
  controllers/administration.js
Labels: waiting for review

#1920 Fix PULL_REQUEST_TEMPLATE typos
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready to merge

#1985 SC-5337 - Finishing login for multi instances
  config/global.js
  controllers/login.js
  views/lib/header.hbs
Labels: ready to merge

#1990 SC-4855 - adds closing span to fix Team Colourpicker
  static/scripts/spectrum/spectrum.js
Labels: ready to merge

#1997 SC-3127 - change-share-icon
  views/courses/course.hbs
Labels: waiting for review

#1988 SC-5265 - lernstore-arrow-back-window
  static/scripts/topicEdit.js
Labels: waiting for review

#1999 SC-4871: Add matrix discover domain to default-src content security policy
  config/http-headers.js
Labels: waiting for review

#1928 i18n SC-5075 Translation static javascripts
  locales/de.json
  static/scripts/videoconference.js
Labels: i18n

#1998 Feature/SC-5571 i18n reroll template,topic
  locales/de.json
  views/template/registration.hbs
  views/topic/components/content-geoGebra.hbs
  views/topic/edit-topic.hbs
  views/topic/topic.hbs
Labels: i18n

#2007 Hotfix/2/sc 5685
  controllers/courses.js
  controllers/teams.js
  package-lock.json
Labels: do_not_merge

#2003 [SC-5645] Imprint Accessibility
  locales/de.json
  theme/brb/views/imprint/imprint_platform-intro.hbs
  theme/brb/views/lib/header.hbs
  theme/n21/views/imprint/imprint_platform-intro.hbs
  theme/n21/views/imprint/imprint_rights.hbs
  theme/n21/views/lib/header.hbs
  theme/open/views/imprint/imprint.hbs
  theme/open/views/lib/header.hbs
  theme/thr/views/imprint/imprint.hbs
  theme/thr/views/lib/header.hbs
  views/imprint/imprint_platform-intro.hbs
  views/imprint/imprint_rights.hbs
  views/lib/forms/form-auto-logout-alert.hbs
  views/lib/header.hbs
  views/lib/loggedin.hbs
Labels: a11y, ready to merge

#2010 [SC-5661] A11y improvement to about page
  static/styles/about/about.scss
  theme/thr/views/about/about.hbs
  views/about/about.hbs
Labels: a11y, ready to merge

#2011 [SC-5716] A11y improvement to addons page
  theme/n21/views/addons/addons.hbs
  views/addons/addons.hbs
Labels: a11y, ready to merge

#2013 [SC-5719] Community page a11y
  views/community/community.hbs
Labels: a11y, ready to merge

#1992 Feature/SC-5514 i18n reroll lib,news,security
  locales/de.json
  static/scripts/dataprivacy/registration-link-validation.js
  views/lib/csrf_content.hbs
  views/lib/default.hbs
  views/lib/error_content.hbs
  views/lib/extended_footer.hbs
  views/lib/extended_footer_links.hbs
  views/lib/footer.hbs
  views/lib/header.hbs
  views/lib/help_menu.hbs
  views/lib/loggedin.hbs
  views/lib/registration.hbs
  views/news/article.hbs
  views/news/edit.hbs
  views/security/security.hbs
Labels: i18n

#1991 Feature/SC-5507 i18n reroll community,imprint,homework
  locales/de.json
  views/community/community.hbs
  views/homework/assignment.hbs
  views/homework/edit.hbs
  views/homework/evaluation.hbs
  views/homework/extended.hbs
  views/homework/feedback.hbs
  views/homework/submission.hbs
  views/homework/submissions.hbs
Labels: i18n, ready to merge

#1865 i18n SC-4852 Translation controller: Administration
  controllers/administration.js
  locales/de.json
Labels: i18n, ready to merge

#2014 i18n static scripts topicEdit
  locales/de.json
  static/scripts/topicEdit.js
Labels: i18n, ready to merge

#2020 Move FEATURE_MULTI_LOGIN_INSTANCES env to schema file
  config/default.schema.json
  config/global.js
  controllers/login.js
Labels: ready to merge

#2021 SC-4925 - change-administration-to-verwaltung
  helpers/handlebars/middleware.js
  locales/de.json
Labels: waiting for review

#2025 SC-5741- cleanup
  theme/brb/views/lib/extended_footer.hbs
  theme/brb/views/lib/footer.hbs
  theme/n21/views/lib/extended_footer.hbs
  theme/open/views/lib/extended_footer.hbs
  theme/open/views/lib/footer.hbs
  theme/thr/views/lib/extended_footer.hbs
  theme/thr/views/lib/footer.hbs
  views/lib/extended_footer.hbs
  views/lib/footer.hbs
Labels: ready to merge

#1891 i18n SC-4805 account
  locales/de.json
  views/account/settings.hbs
Labels: i18n, ready to merge

#2026 SC-5608 - rename-material-button-in-courses
  locales/de.json
Labels: waiting for review

#1961 [SC-4973] rename FEATURE_ADMIN_TOGGLE_STUDENT_VISIBILITY
  config/default.schema.json
  controllers/administration.js
  views/administration/school.hbs
Labels: ready to merge

#2018 SC-5644 - a11y, skip links for navigation
  locales/de.json
  static/styles/lib/base.scss
  static/styles/lib/loggedin.scss
  theme/brb/views/authentication/home.hbs
  theme/brb/views/lib/default.hbs
  theme/brb/views/lib/extended_footer.hbs
  theme/brb/views/lib/footer.hbs
  theme/brb/views/lib/simple.hbs
  theme/n21/views/authentication/home.hbs
  theme/n21/views/lib/extended_footer.hbs
  theme/n21/views/lib/footer.hbs
  theme/n21/views/lib/header.hbs
  theme/n21/views/lib/simple.hbs
  theme/open/views/authentication/home.hbs
  theme/open/views/lib/default.hbs
  theme/open/views/lib/extended_footer.hbs
  theme/open/views/lib/footer.hbs
  theme/open/views/lib/simple.hbs
  theme/thr/views/lib/default.hbs
  theme/thr/views/lib/extended_footer.hbs
  theme/thr/views/lib/footer.hbs
  views/lib/csrf.hbs
  views/lib/default.hbs
  views/lib/error.hbs
  views/lib/extended_footer.hbs
  views/lib/footer.hbs
  views/lib/header.hbs
  views/lib/loggedin.hbs
  views/lib/registration.hbs
Labels: a11y, ready to merge

#2019 SC-5644 a11l improved accessibility of login form
  locales/de.json
  static/styles/homepage/login.scss
  views/authentication/forms/login.hbs
Labels: a11y, ready to merge

#2022 SC-5686 - team can only be edited with permission
  CHANGELOG.md
  controllers/courses.js
  controllers/teams.js
Labels: ready to merge

#2023 Quickfix - Update team page
  helpers/content/team.js
Labels: ready to merge

#2004 SC-4275 - SC International Legacy Theming
  Dockerfile.int
  build.sh
  theme/int/static/images/logo/logo.svg
  theme/int/static/images/manifest.json
  theme/int/style.scss
Labels: ready to merge

#2032 SC-5765 - switched logos n21, general fix
  theme/int/static/images/logo/logo.svg
  theme/n21/static/images/logo/cloud-transparent-mono-48-48.svg
  theme/n21/static/images/logo/cloud-transparent-mono.svg
Labels: ready to merge

#1801 [#SC-4064] Change download file names (3+4/4)
  .editorconfig
  CHANGELOG.md
  controllers/homework.js
  helpers/handlebars/helpers/index.js
  helpers/homework.js
  locales/de.json
  static/scripts/homework.js
  static/scripts/homework/api-requests.js
  static/scripts/homework/bulk-upload.js
  static/styles/homework/bulk-upload.scss
  static/styles/homework/file-upload.scss
  static/styles/homework/submissions.scss
  test/mocha/homework/helpers.test.js
  views/files/file-upload.hbs
  views/homework/components/bulk-grading.hbs
  views/homework/components/submission_files.hbs
  views/homework/evaluation.hbs
  views/homework/feedback.hbs
  views/homework/submission.hbs
  views/homework/submissions.hbs
Labels: ready to merge

#1889 i18n SC-4762 firstLogin
  locales/de.json
  views/firstLogin/consentError.hbs
  views/firstLogin/firstLogin.hbs
  views/firstLogin/firstLoginExistingUser.hbs
  views/firstLogin/partials/language-hint.hbs
  views/firstLogin/partials/welcome_existing.hbs
  views/firstLogin/sections/birthdate.hbs
  views/firstLogin/sections/birthdate_U14.hbs
  views/firstLogin/sections/birthdate_UE14.hbs
  views/firstLogin/sections/birthdate_UE16.hbs
  views/firstLogin/sections/consent.hbs
  views/firstLogin/sections/consent_updates.hbs
  views/firstLogin/sections/email.hbs
  views/firstLogin/sections/parent_consent.hbs
  views/firstLogin/sections/parent_data.hbs
  views/firstLogin/sections/parent_intro.hbs
  views/firstLogin/sections/password.hbs
  views/firstLogin/sections/pin.hbs
  views/firstLogin/sections/thanks.hbs
  views/firstLogin/sections/welcome.hbs
  views/firstLogin/sections/welcome_14-15.hbs
  views/firstLogin/sections/welcome_existing_geb14.hbs
  views/firstLogin/welcome.hbs
Labels: i18n, ready to merge

#2029 SC-5560 - provide-click-dummy
  static/styles/homepage/index.scss
  views/authentication/home.hbs
Labels: ready to merge

#1955 SC-4997 force user to change password if the password was changed by …
  controllers/administration.js
  controllers/forcePasswordChange.js
  controllers/index.js
  controllers/login.js
  helpers/authentication.js
  static/scripts/dataprivacy/forcePasswordChange.js
  test/mocha/forcePasswordChange/forcePasswordChange.test.js
  views/firstLogin/forcePasswordChange.hbs
  views/firstLogin/partials/importsForcePasswordChange.hbs
Labels: ready to merge

#2009 i18n SC-4821 Translation_HELP
  locales/de.json
  static/scripts/help.js
  views/community/community.hbs
  views/help/confluence.hbs
  views/help/contact-card.hbs
  views/help/dashboard.hbs
  views/help/forms/form_admin.hbs
  views/help/forms/form_bug.hbs
  views/help/forms/form_wish.hbs
  views/help/help.hbs
  views/help/language-hint.hbs
  views/help/lern-nuggets.hbs
  views/help/mail-card.hbs
  views/help/partials/help_about.hbs
  views/help/partials/help_confluence_links.hbs
  views/help/partials/help_contact.hbs
  views/help/partials/help_first_steps.hbs
  views/help/partials/help_form_invite_external_members.hbs
  views/help/partials/login_failed_hint.hbs
  views/help/people.hbs
  views/help/releases.hbs
Labels: i18n

#2044 add deployment output commands
  deploy.sh
Labels: auto update, ready to merge

#2039 [SC-5730] A11y to account page
  helpers/handlebars/middleware.js
  locales/de.json
  static/scripts/pwd.js
  views/account/settings.hbs
  views/authentication/forms/login.hbs
Labels: a11y, ready to merge

#2033 SC-5644 - footer
  locales/de.json
  static/styles/lib/base.scss
  theme/brb/views/lib/extended_footer.hbs
  theme/brb/views/lib/footer.hbs
  theme/n21/views/lib/extended_footer.hbs
  theme/n21/views/lib/footer.hbs
  theme/open/views/lib/extended_footer.hbs
  theme/open/views/lib/footer.hbs
  theme/thr/views/lib/extended_footer.hbs
  theme/thr/views/lib/footer.hbs
  views/lib/extended_footer.hbs
  views/lib/extended_footer_links.hbs
  views/lib/footer.hbs
  views/lib/loggedin.hbs
Labels: a11y, ready to merge

#2016 SC-5340 fix xss vurnelable input in teams by sanitizing its content
  static/scripts/helpers/inputLinking.js
Labels: ready to merge

#2027 SC-5644 - a11y topbar
  locales/de.json
  static/styles/lib/base.scss
  static/styles/lib/bootstrap/scss/_dropdown.scss
  views/lib/help_menu.hbs
  views/lib/loggedin.hbs
Labels: a11y, ready to merge
