Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2020-12, with the labels that each got.

#2369 Add populating of federalstates in school edit page
  CHANGELOG.md
  controllers/administration.js
  locales/de.json
Labels: waiting for review

#2372 SC-7900 - text changes for people invite
  CHANGELOG.md
  locales/de.json
  locales/en.json
  theme/n21/views/help/partials/help_form_invite_external_members.hbs
  theme/n21/views/help/partials/help_form_note.hbs
  views/teams/forms/form-invite-external-member.hbs
Labels: auto update, ready to merge

#2382 Hotfix/4/sc 8075 nbc ghost
  CHANGELOG.md
  package-lock.json
  package.json
  static/scripts/theme-blog.js
Labels: waiting for review

#2384 Hotfix/4/SC-8075 nbc ghost to Release
  CHANGELOG.md
  package-lock.json
  package.json
  static/scripts/theme-blog.js
  theme/n21/views/help/mail-card.hbs
Labels: waiting for review

#2385 Hotfix/4/SC-8075 merge to Develop
  CHANGELOG.md
  package-lock.json
  package.json
  static/scripts/theme-blog.js
Labels: auto update, waiting for review

#2388 Hotfix/4/SC-8075 merge to release
  CHANGELOG.md
  static/scripts/theme-blog.js
Labels: waiting for review

#2343 set in docker e2e test startup script
  .travis.yml
  CHANGELOG.md
Labels: auto update, ready to merge

#2383 hotfix/SC-8080-wrong course times
  CHANGELOG.md
  helpers/recurringEvents.js
  package-lock.json
  package.json
  test/mocha/helper/recurringEvents.test.js
Labels: auto update

#2378 SC-8053 - added spacing on homework page
  views/homework/extended.hbs
Labels: ready to merge

#2380 Feature/SC-7793 Changing the ldap edit link on edit button
  CHANGELOG.md
  controllers/administration.js
  static/scripts/administration/systems/ldap-edit.js
  views/administration/forms/form-ldap-edit.hbs
  views/administration/school.hbs
Labels: auto update, auto_merged, ready to merge

#2395 SC-6347 - UI inconsistencies old client
  views/administration/users_edit.hbs
Labels: ready to merge

#2398 SC-8176 - fix course events. Edge cases
  helpers/recurringEvents.js
  test/mocha/helper/recurringEvents.test.js
Labels: auto update

#2403 SC-6975 - Fertig button instead of zuruck
  CHANGELOG.md
  controllers/administration.js
  locales/de.json
  locales/en.json
  views/administration/users_registrationcomplete.hbs
Labels: auto update, waiting for review

#2400 SC-8220 Hotfix/25.3.5/skipable calendar dashboard request
  .github/workflows/require_changelog.yml
  CHANGELOG.md
  config/default.schema.json
  config/global.js
  controllers/administration.js
  controllers/courses.js
  controllers/dashboard.js
  controllers/helpdesk.js
  controllers/teams.js
  package-lock.json
  package.json
Labels: ready to merge

#2404 SC-7848 - no autofill of password in user settings
  CHANGELOG.md
  controllers/courses.js
  controllers/dashboard.js
  controllers/helpdesk.js
  views/account/settings.hbs
Labels: auto update, do_not_merge

#2406 SC-7126 - added sorting years
  CHANGELOG.md
  controllers/administration.js
Labels: auto update, waiting for review

#2414 feature/SC-7889 - shd consent screen
  CHANGELOG.md
  locales/de.json
  locales/en.json
  views/firstLogin/sections/consent_updates.hbs
Labels: waiting for review

#2408 SC-7824 - Set proper labels and emails in some places regarding data protection
  CHANGELOG.md
  locales/de.json
  locales/en.json
  theme/brb/views/lib/extended_footer.hbs
  views/lib/extended_footer_links.hbs
Labels: auto update, waiting for review

#2116 SC-5710 courses a11y
  CHANGELOG.md
  locales/de.json
  locales/en.json
  package-lock.json
  static/scripts/dataprivacy/paginated_form.js
  static/styles/courses/course-edit.scss
  static/styles/courses/course.scss
  views/courses/components/courseGroup-card.hbs
  views/courses/components/groups.hbs
  views/courses/components/tasks.hbs
  views/courses/components/template-new-course-time.hbs
  views/courses/components/tools.hbs
  views/courses/components/topics.hbs
  views/courses/create-course.hbs
  views/courses/edit-course.hbs
  views/courses/forms/form-import-course.hbs
  views/courses/overview.hbs
  views/lib/csrf_content.hbs
  views/lib/default.hbs
  views/lib/forms/paginatedForm.hbs
  views/lib/loggedin.hbs
Labels: a11y, auto update, waiting for review

#2416 SC-8272 - Error message shown even without submission date
  CHANGELOG.md
  controllers/homework.js
  views/homework/assignment.hbs
Labels: waiting for review

#2418 SC-5710 - small fixes for the course page
  CHANGELOG.md
  static/styles/homework/homework.scss
  views/homework/feedback.hbs
  views/registration/registration-parent.hbs
  views/registration/registration-student.hbs
Labels: waiting for review
