Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2020-10, with the labels that each got.

#2239 Hotfix SC-6973
  CHANGELOG.md
  controllers/registration.js
  package-lock.json
  package.json
  static/scripts/dataprivacy/pin.js
Labels: waiting for review

#2221 SC-6391 Bugfix mobile header menu
  static/styles/lib/loggedin.scss
Labels: auto update, ready to merge

#2182 SC-6674: check for unique emails. Show error if failed
  controllers/administration.js
Labels: auto update, waiting for review

#2223 Feature/sc 6655 add data testids
  views/lib/loggedin.hbs
  views/news/overview.hbs
  views/teams/overview.hbs
Labels: ready to merge

#2168 i18n SC-6641 improvements
  controllers/administration.js
  locales/de.json
  locales/en.json
  static/scripts/settings.js
  theme/n21/views/firstLogin/partials/welcome_existing.hbs
  views/account/settings.hbs
  views/account/teams.hbs
  views/administration/classes_skipregistration.hbs
  views/administration/forms/form-classes-edit.hbs
  views/administration/forms/form-classes-manage.hbs
  views/administration/forms/form-delete-user.hbs
  views/administration/forms/form-ldap-edit.hbs
  views/administration/forms/form-rss.hbs
  views/administration/ldap-schoolyear-start.hbs
  views/administration/school.hbs
  views/administration/teachers.hbs
  views/administration/users_registrationcomplete.hbs
  views/courses/components/svg_archived_courses.hbs
  views/courses/overview.hbs
  views/firstLogin/components/welcome_greeting.hbs
  views/firstLogin/partials/welcome_existing.hbs
  views/help/contact-card.hbs
  views/template/registration.hbs
Labels: auto update, i18n, waiting for review

#2245 SC-7052 - new conditions for ux approve
  .pullapprove.yml
Labels: auto update, ready to merge

#2209 SC-5858: a11y dropdowns
  CHANGELOG.md
  gulpfile.js
  locales/de.json
  locales/en.json
  static/scripts/administration/classes/edit.js
  static/scripts/administration/classes/manage.js
  static/scripts/base.js
  static/scripts/calendar.js
  static/scripts/chosen/chosen.jquery.min.js
  static/scripts/coursesTimes.js
  static/scripts/homework.js
  static/scripts/login.js
  static/scripts/pwd.js
  static/styles/lib/base.scss
  views/authentication/forms/login.hbs
  views/courses/components/template-new-course-time.hbs
  views/courses/create-course.hbs
  views/files/files.hbs
  views/homework/edit.hbs
  views/lib/help_menu.hbs
Labels: a11y, waiting for review

#2229 SC-6870 Improve matrix announcement
  CHANGELOG.md
  controllers/administration.js
  locales/de.json
  locales/en.json
  static/images/messenger-info.svg
  static/scripts/deprecationInfoRocketChat.js
  static/scripts/messenger/welcome.js
  views/administration/school.hbs
  views/lib/loggedin.hbs
Labels: waiting for UX review

#2253 Hotfix/3/show consent update
  CHANGELOG.md
  controllers/firstLogin.js
  package-lock.json
  package.json
Labels: ready to merge

#2227 SC-6582 Add bidirectional course messenger settings
  CHANGELOG.md
  controllers/courses.js
  views/courses/create-course.hbs
  views/teams/edit-team.hbs
Labels: auto update, ready to merge

#2251 using form-input-data
  controllers/administration.js
  controllers/registration.js
  helpers/timesHelper.js
  static/scripts/jquery/datetimepicker-easy.js
  test/mocha/i18n/i18n.test.js
  views/administration/administration.hbs
  views/administration/classes_skipregistration.hbs
  views/administration/forms/form-students.hbs
  views/administration/users_edit.hbs
  views/administration/users_skipregistration.hbs
  views/firstLogin/sections/birthdate.hbs
  views/firstLogin/sections/birthdate_U14.hbs
  views/firstLogin/sections/birthdate_UE14.hbs
  views/firstLogin/sections/birthdate_UE16.hbs
  views/lib/forms/form-date-input.hbs
  views/lib/forms/form-datetime-input.hbs
  views/registration/registration-parent.hbs
  views/registration/registration-student.hbs
Labels: auto update

#2249 SC-7082 - csrf token required when loging out
  controllers/login.js
  helpers/csrf.js
  static/scripts/loggedin.js
  views/lib/loggedin.hbs
Labels: waiting for review

#2259 Fix news edit and removed news methods that have moved to vue
  controllers/news.js
  static/scripts/news.js
Labels: auto update

#2258 Adding specific time error message to csv import
  config/development.json
  controllers/administration.js
  locales/de.json
  locales/en.json
Labels: auto update, waiting for review

#2137 SC-6442: topics a11y
  locales/de.json
  locales/en.json
  package-lock.json
  package.json
  static/scripts/courses.js
  static/scripts/topicEdit.js
  static/styles/courses/course.scss
  static/styles/homework/homework.scss
  views/courses/components/topics.hbs
  views/courses/forms/form-import-topic.hbs
  views/lib/components/modal.hbs
  views/lib/components/notification.hbs
  views/team/team.hbs
  views/topic/edit-topic.hbs
  views/topic/forms/form-share.hbs
  views/topic/topic.hbs
Labels: a11y, auto update, waiting for review

#2145 Feature/SC-6479 fixing grammar issues
  locales/de.json
Labels: auto update

#2267 Fixing sentence structure parents in registration
  CHANGELOG.md
  locales/de.json
Labels: auto update, ready to merge

#2264 SC-7085 - fixes parent consent pin request
  CHANGELOG.md
  package-lock.json
  package.json
  views/firstLogin/firstLogin.hbs
  views/firstLogin/sections/pin.hbs
Labels: waiting for review

#2265 SC-6156 - last row table border fix
  package-lock.json
  static/styles/homework/submissions.scss
Labels: auto update, ready to merge, waiting for review

#2252 Feature/SC-6060 - Analyse and fix top errors in sentry
  CHANGELOG.md
  app.js
  controllers/registration.js
  helpers/authentication.js
  helpers/cookieHelper.js
  middleware/i18n.js
  static/scripts/cleanup.js
  static/scripts/homework.js
  static/scripts/loggedin.js
  static/scripts/login.js
  test/mocha/helpers/cookieHelper.test.js
Labels: waiting for review

#2277 SC-7392 show course / teams dropdown by event creation
  CHANGELOG.md
  locales/de.json
  locales/en.json
  static/scripts/calendar.js
  views/calendar/forms/form-create-event.hbs
Labels: auto update, auto_merged

#2273 change move icon in course topics
  CHANGELOG.md
  locales/de.json
  locales/en.json
  views/courses/components/topics.hbs
Labels: auto update, ready to merge

#2276 hotfix/1/SC-7434 - qr code name of username fix
  CHANGELOG.md
  package-lock.json
  package.json
  static/scripts/administration/classes/manage.js
Labels: auto update, ready to merge, waiting for review

#2272 fixed link names and adding privacy name
  CHANGELOG.md
  theme/n21/views/lib/extended_footer.hbs
  theme/open/views/lib/extended_footer.hbs
  theme/thr/views/lib/extended_footer.hbs
Labels: auto update, ready to merge

#2278 hotfix/1/SC-7434 - qr code name of username fix
  CHANGELOG.md
  static/scripts/administration/classes/manage.js
Labels: auto update, ready to merge, waiting for review

#2270 Feature/SC - 7083 get school id from admin
  CHANGELOG.md
  controllers/schools.js
  locales/de.json
  locales/en.json
  views/administration/school.hbs
Labels: ready to merge

#2279 SC-7443 set trust proxy setting
  app.js
Labels: auto update, ready to merge

#2281 feature/SC-6951 - remove via text from embedded course-content
  CHANGELOG.md
  static/scripts/topicEdit.js
Labels: auto update, ready to merge

#2282 SC-7463 - fix schoolId value
  CHANGELOG.md
  static/scripts/login.js
Labels: auto update, ready to merge

#2285 Feature/sc 7447 add warning text leaving sc
  CHANGELOG.md
  locales/de.json
  locales/en.json
  static/scripts/topicEdit.js
  static/styles/courses/course.scss
  views/topic/components/content-resources.hbs
  views/topic/topic.hbs
Labels: waiting for review

#2284 show classes in course administration
  CHANGELOG.md
  controllers/administration.js
Labels: auto update

#2260 SC-5825 Removed Circular progress, added HTML5 progress and translated text
  CHANGELOG.md
  locales/de.json
  locales/en.json
  static/styles/homework/homework.scss
  static/vendor/m.e.i.n.e.l/m.e.i.n.e.l.min.html
  static/vendor/webcomponents-bundle.js
  static/vendor/webcomponents-lite.js
  views/homework/components/overview_card_template.hbs
  views/homework/overview.hbs
Labels: auto update

#2261 SC-3961 show grade also if value eq 0
  views/homework/feedback.hbs
Labels: auto update, ready to merge

#2290 Fix progress style
  static/styles/homework/homework.scss
Labels: ready to merge

#2299 fixed grammar issue for password recovery
  CHANGELOG.md
  locales/de.json
Labels: ready to merge

#2298 hotfix/1/SC-7490 - landing page get request fix
  CHANGELOG.md
  package-lock.json
  package.json
  theme/brb/views/authentication/home.hbs
  theme/open/views/authentication/home.hbs
  theme/thr/views/authentication/home.hbs
Labels: waiting for review

#2297 SC-6870 Improve dont show again checkbox handling
  CHANGELOG.md
  package-lock.json
  static/scripts/messenger/welcome.js
Labels: auto update, ready to merge

#2292 change file permission naming
  CHANGELOG.md
  locales/de.json
  locales/en.json
  static/scripts/files.js
Labels: ready to merge

#2300 SC-6354 - fix not necessary page reload
  views/help/dashboard.hbs
Labels: auto update, waiting for review

#2301 SC-6870 fix rocket chat condition in school admin area
  views/administration/school.hbs
Labels: auto update, ready to merge

#2303 SC-7502 - hotfix/fix registration link buttons
  CHANGELOG.md
  package-lock.json
  package.json
  views/administration/users_edit.hbs
Labels: do_not_merge

#2306 Feature/sc 7413/add logger options
  CHANGELOG.md
  helpers/logger.js
Labels: auto update, ready to merge

#2304 SC-7040 - landing-page-international-fix
  static/scripts/theme-blog.js
Labels: auto update, waiting for review

#2307 SC-5555 - class name not visible in course creation fix
  CHANGELOG.md
  views/courses/create-course.hbs
Labels: auto update, ready to merge

#2308 SC-6582 Fix variable name to access school data
  views/courses/create-course.hbs
Labels: auto update, ready to merge

#2110 SC-6120: files a11y
  locales/de.json
  locales/en.json
  static/scripts/files.js
  static/styles/files/files.scss
  static/styles/lib/base.scss
  views/files/file-viewer.hbs
  views/files/files-grid.hbs
  views/files/files-overview.hbs
  views/files/files.hbs
  views/files/forms/form-file-permissions.hbs
  views/files/forms/form-name-edit.hbs
  views/files/forms/form-share-file.hbs
  views/lib/components/sc-card.hbs
  views/teams/team.hbs
Labels: a11y, auto update, waiting for review

#2309 SC-7530 rename SHOW_VERSION
  CHANGELOG.md
  config/default.json
  config/default.schema.json
  config/production.json
  controllers/version.js
Labels: ready to merge

#2310 SC-7531 Translation issues with role Expert
  locales/de.json
  locales/en.json
Labels: auto update, ready to merge, waiting for review

#2314 feature/IMP-160/rename integration test repository
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  CHANGELOG.md
Labels: waiting for review
