Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2020-01, with the labels that each got.

#1549 add clickable badges that indicates task-category
  static/styles/homework/homework.scss
  static/styles/homework/overview.scss
  views/homework/components/overview_card_template.hbs
Labels: ready to merge

#1552 SC-3014-expert-teams-helptext
  views/teams/overview-empty.hbs
  views/teams/overview.hbs
Labels: waiting for review

#1548 Remove Intro Link on Landing Page
  gulpfile.js
  helpers/handlebars/middleware.js
  static/scripts/base.js
  static/scripts/loggedin.js
  static/scripts/login.js
  static/styles/authentication/home.scss
  static/styles/lib/base.scss
  static/styles/lib/loggedin.scss
  static/vendor/introjs/intro.min.js
  static/vendor/introjs/introjs-rtl.min.css
  static/vendor/introjs/introjs.min.css
  test/mocha/content/content.test.js
  theme/n21/views/lib/help_menu.hbs
  theme/open/views/authentication/home.hbs
  theme/thr/views/authentication/home.hbs
  views/authentication/forms/demo-login.hbs
  views/authentication/forms/login.hbs
  views/authentication/home.hbs
  views/dashboard/components/card_section.hbs
  views/dashboard/dashboard.hbs
  views/lib/header.hbs
  views/lib/help_menu.hbs
  views/lib/loggedin.hbs
Labels: ready to merge

#1553 SC-2991-new-lernen.cloud-links
  theme/brb/views/help/partials/help_nutzungshilfen.hbs
  theme/open/views/help/partials/help_nutzungshilfen.hbs
  theme/thr/views/help/partials/help_nutzungshilfen.hbs
  views/help/partials/help_nutzungshilfen.hbs
Labels: ready to merge

#1558 Feature/sc 3093 uploader homework creation
  controllers/homework.js
  static/scripts/homework.js
  static/styles/homework/file-upload.scss
  views/files/file-upload.hbs
  views/homework/assignment.hbs
  views/homework/components/homework_uploaded_files.hbs
  views/homework/components/submission_uploaded_files.hbs
  views/homework/edit.hbs
  views/homework/extended.hbs
  views/homework/submission.hbs
Labels: waiting for review

#1564 implement SC-3135 - gender demo login
  views/authentication/forms/demo-login.hbs
Labels: ready to merge

#1518 WIP: Add SSO for Thueringen
  controllers/login.js
  helpers/authentication.js
Labels: WIP

#1539 SC-689-homework-page-on-delete
  static/scripts/homework.js
  views/homework/components/overview_card_template.hbs
Labels: ready to merge

#1576 SC-2418 Direktes Öffnen von PDFs durch Browserpreview
  controllers/files.js
  static/scripts/files.js
  views/files/files-grid.hbs
Labels: ready to merge

#1572 remove David from team page
  helpers/content/team.js
  static/images/team/David_Jäger.jpg
Labels: ready to merge

#1566 SC-2513 fix registration for detect, and disable second registration .form not found
  static/scripts/dataprivacy/registration-link-validation.js
  static/scripts/dataprivacy/registration.js
  static/scripts/dataprivacy/user-registration.js
  views/registration/registration-employee.hbs
  views/registration/registration-parent.hbs
  views/registration/registration-student.hbs
Labels: ready to merge

#1569 SC-3148 copy button in details for tasks
  views/homework/extended.hbs
Labels: ready to merge

#1570 SC-2034 | lern-nuggets integration
  controllers/help.js
  theme/brb/views/help/lern-nuggets.hbs
  theme/n21/views/help/lern-nuggets.hbs
  theme/open/views/help/lern-nuggets.hbs
  theme/thr/views/help/lern-nuggets.hbs
  views/help/lern-nuggets.hbs
  views/help/partials/help_nutzungshilfen.hbs
Labels: ready to merge

#1510 SC-1247 | Removed "Kurs löschen"-button for substitute teacher
  controllers/courses.js
  views/courses/course.hbs
  views/courses/edit-course.hbs
Labels: ready to merge

#1589 SC-2623-week-start-monday
  static/scripts/jquery/datetimepicker-easy.js
  static/scripts/teams.js
  views/homework/edit.hbs
Labels: ready to merge

#1591 Hotfix/20.2.3
  package-lock.json
  package.json
  views/homework/extended.hbs
Labels: ready to merge

#1594 fix wrong document in brb footer
  theme/brb/views/lib/footer.hbs
Labels: ready to merge
