Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2021-01, with the labels that each got.

#2422 SC-7345 - Unnötiger Gender-Disclaimer im Englischen
  CHANGELOG.md
  views/firstLogin/partials/language-hint.hbs
  views/help/confluence.hbs
  views/help/contact.hbs
  views/help/help.hbs
  views/registration/registration-employee.hbs
  views/registration/registration.hbs
Labels: waiting for review

#2421 SC-8259: task title shortened
  CHANGELOG.md
  static/styles/homework/homework.scss
  static/styles/lib/base.scss
  static/styles/lib/loggedin.scss
  views/homework/edit.hbs
Labels: waiting for review

#2415 Fix naming convention for Lern Store
  CHANGELOG.md
  locales/en.json
Labels: waiting for review

#2419 SC-7824 - privacy email changed for newsletter and text_datenverarbeit…
  CHANGELOG.md
  theme/n21/views/dataprivacy/privacy_newsletter.hbs
  views/dataprivacy/text_datenverarbeitung-web.hbs
Labels: waiting for review

#2429 SC-8356 add docker login helper from docker-compose repo for mocha tests
  .travis.yml
  CHANGELOG.md
Labels: ready to merge

#2374 Add warning label
  CHANGELOG.md
  locales/de.json
  locales/en.json
  package-lock.json
  views/administration/school.hbs
Labels: waiting for review

#2424 SC-8331 use lts/* as node version
  .nvmrc
  .travis.yml
  CHANGELOG.md
  Dockerfile
  Dockerfile.brb
  Dockerfile.demo
  Dockerfile.int
  Dockerfile.n21
  Dockerfile.open
  Dockerfile.thr
Labels: ready to merge

#2442 Hotfix/1/sc 8189 course event duplication
  CHANGELOG.md
  controllers/courses.js
  package-lock.json
  package.json
Labels: auto update, do_not_merge

#2444 SC-8404 – Text for missing schedule needs to be adjusted to reduce tickets in user support
  locales/de.json
  locales/en.json
Labels: auto update, auto_merged, waiting for review

#2449 Update wordlist.js
  static/other/wordlist.js
Labels: ready to merge

#2452 SC-8531 - Restored school administration missing text
  CHANGELOG.md
  locales/de.json
  locales/en.json
  views/administration/school.hbs
Labels: auto update, auto_merged, ready to merge
