Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2021-09, with the labels that each got.

#2664 BC-38 - BC-125 - Add ansible files for Bosscloud (default)
  CHANGELOG.md
  ansible/group_vars/default/schulcloud-client.yml
Labels: waiting for review, run tests

#2662 BC-137 - fix display of Blue Bar message
  CHANGELOG.md
  package-lock.json
  package.json
  views/lib/loggedin.hbs
Labels: run tests

#2665 Feature/sc 9083 vuetify admin schools
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
  views/administration/school.hbs
Labels: waiting for review, run tests

#2666 Feature/bc 94 color clean up
  CHANGELOG.md
  static/images/logo/cloud-transparent-mono-48-48.svg
  static/images/logo/cloud-transparent-mono.svg
  static/styles/authentication/home.scss
  static/styles/courses/course.scss
  static/styles/homepage/login.scss
  static/styles/lib/bootstrap/scss/_custom.scss
  static/styles/lib/bootstrap/scss/_dropdown.scss
  static/styles/lib/bootstrap/scss/_navbar.scss
  static/styles/lib/bootstrap/scss/_variables.scss
  static/styles/lib/colors.scss
  static/styles/lib/loggedin.scss
  static/styles/lib/sc-theme/sc-card.scss
  static/styles/lib/tabbar/tabbar.scss
  theme/brb/static/images/logo/cloud-transparent-mono-48-48.svg
  theme/brb/static/images/logo/cloud-transparent-mono-long.svg
  theme/brb/static/images/logo/cloud-transparent-mono.svg
  theme/brb/style.scss
  theme/default/style.scss
  theme/demo/style.scss
  theme/int/static/images/logo/cloud-transparent-mono-48-48.svg
  theme/int/static/images/logo/cloud-transparent-mono.svg
  theme/int/style.scss
  theme/n21/static/images/logo/cloud-transparent-mono-48-48.svg
  theme/n21/static/images/logo/cloud-transparent-mono-long.svg
  theme/n21/static/images/logo/cloud-transparent-mono.svg
  theme/n21/style.scss
  theme/open/static/images/logo/cloud-transparent-mono-48-48.svg
  theme/open/static/images/logo/cloud-transparent-mono.svg
  theme/open/style.scss
  theme/thr/static/images/logo/cloud-transparent-mono-48-48.svg
  theme/thr/static/images/logo/cloud-transparent-mono.svg
  theme/thr/static/images/logo/logo-mono.svg
  theme/thr/style.scss
  views/authentication/forms/login.hbs
Labels: waiting for review, waiting for UX review, auto_merged, auto update, run tests

#2669 Feature/bc 94 add fix issue
  CHANGELOG.md
  static/styles/lib/loggedin.scss
Labels: waiting for review, auto update

#2667 Feature/bc 229 exchange private task into draft
  CHANGELOG.md
  controllers/administration.js
  controllers/homework.js
  locales/de.json
  locales/en.json
  locales/es.json
  views/administration/courses.hbs
  views/courses/components/tasks.hbs
  views/courses/overview.hbs
  views/dashboard/dashboard.hbs
  views/homework/components/overview_card_template.hbs
  views/homework/edit.hbs
  views/teams/topics.hbs
  views/topic/topic.hbs
Labels: waiting for review, auto update, run tests

#2668 BC-239 - normalize students birth date
  CHANGELOG.md
  controllers/firstLogin.js
  helpers/date.js
  package-lock.json
  package.json
  test/mocha/helpers/date.test.js
Labels: waiting for review, run tests

#2675 Feature/bc 242 fix topic visibility
  CHANGELOG.md
  controllers/topics.js
  static/scripts/courses.js
Labels: run tests

#2670 make make sure e2e comes after build
  .github/workflows/build_push_service.yml
  .github/workflows/push.yml
  .github/workflows/test_e2e_pull_request.yml
  .github/workflows/test_e2e_push_main.yml
  CHANGELOG.md
Labels: waiting for review

#2674 Feature/bc 235 create course colors
  CHANGELOG.md
  controllers/courses.js
  package-lock.json
  package.json
  static/styles/courses/course-edit.scss
  static/styles/lib/loggedin.scss
  static/styles/lib/sc-theme/sc-card.scss
  theme/brb/style.scss
  views/administration/forms/form-courses.hbs
  views/courses/create-course.hbs
Labels: ready to merge, run tests

#2678 BC-217 - update LibreOffic domain at http-headers.js on ansible client-configmap-files.yml.j2
  CHANGELOG.md
  ansible/roles/schulcloud-client/templates/client-configmap-files.yml.j2
  ansible/roles/schulcloud-client/templates/configmap.yml.j2
Labels: waiting for review, run tests

#2680 BC-331 - BC-354 - rename ansible variables for OnePassword
  CHANGELOG.md
  ansible/roles/schulcloud-client/tasks/main.yml
  ansible/roles/schulcloud-client/templates/onepassword.yml.j2
Labels: waiting for review
