Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2021-11, with the labels that each got.

#2688 BC-392 - adjusted skip links wording
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
Labels: run tests

#2702 BC-402 - change e2e test include to reusable workflows
  .github/workflows/push.yml
  CHANGELOG.md
Labels: run unstable tests

#2699 Teacher can add students from other schools to own team
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
  static/scripts/teamMembers.js
Labels: run tests

#2713 BC-589 - BC-651 - Change auto deployment to a reusable workflow
  .github/workflows/clean.yml
  .github/workflows/push.yml
  CHANGELOG.md
Labels: waiting for review

#2715 BC-597 - update mathjax
  CHANGELOG.md
  package-lock.json
  package.json
Labels: run unstable tests

#2717 version 26.17.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: waiting for review

#2712 Fixing success message for permission saving in teams
  CHANGELOG.md
  static/scripts/teams.js
Labels: waiting for review, run tests

#2718 BC-700 Fix deletion for files in tasks
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
  static/scripts/homework.js
Labels: waiting for review, run unstable tests

#2720 BC-740 change ansible vars for docker image and tag
  CHANGELOG.md
  ansible/group_vars/all/schulcloud-client.yml
  ansible/roles/schulcloud-client/templates/deployment.yml.j2
Labels: waiting for review
