Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2021-02, with the labels that each got.

#2454 SC-8157 usability filters last minute update
  views/files/files.hbs
Labels: auto_merged

#2457 made school number field editable for ldap schools
  CHANGELOG.md
  views/administration/school.hbs
Labels: ready to merge

#2470 SC-8408: delete by scope route
  CHANGELOG.md
  controllers/courses.js
Labels: auto update

#2436 SC-8416 Fix logo display on subpages by making path absolute
  CHANGELOG.md
  static/styles/oauth2/username.scss
  theme/brb/style.scss
  theme/default/style.scss
  theme/demo/style.scss
  theme/int/style.scss
  theme/n21/style.scss
  theme/open/style.scss
  theme/thr/style.scss
Labels: auto update, ready to merge

#2465 SC-8597 – Course name title has wrong color
  CHANGELOG.md
  static/styles/courses/course.scss
Labels: waiting for review

#2475 SC - 8565 long text not wrapping
  views/courses/course.hbs
  views/lib/components/sc-card.hbs
Labels: auto update

#2464 SC-8594–drag icon on the topic card is not visible
  CHANGELOG.md
  static/styles/courses/course.scss
Labels: auto update, auto_merged, ready to merge

#2474 SC-6923 fixed help area search by changing request url
  CHANGELOG.md
  static/scripts/help.js
  views/help/confluence.hbs
Labels: auto update, ready to merge

#2476 SC-8618 - follow up fixes for introducing Spanish to the client
  CHANGELOG.md
  controllers/help.js
  helpers/handlebars/middleware.js
  locales/de.json
  locales/en.json
  locales/es.json
  static/scripts/calendar.js
  views/help/search.hbs
Labels: auto update, ready to merge

#2473 SC-8341: fix bug with teams with deleted user
  CHANGELOG.md
  controllers/teams.js
Labels: auto update

#2479 SC-8609 – remove hpi e-mail adresses from the contact area of different plattforms
  CHANGELOG.md
  theme/brb/views/help/people.hbs
  theme/int/views/help/mail-card.hbs
  theme/thr/views/help/people.hbs
Labels: auto update, auto_merged

#2478 SC-8408: return delete response
  CHANGELOG.md
  controllers/courses.js
Labels: auto update, auto_merged, ready to merge

#2477 SC-8575 - layout issue in tasks
  CHANGELOG.md
  views/homework/components/overview_card_template.hbs
  views/lib/extended_footer_links.hbs
Labels: auto update, auto_merged

#2481 Sanitize prometheus metrics route for link hashes
  CHANGELOG.md
  config/development.json
  helpers/prometheus.js
  package-lock.json
  package.json
Labels: waiting for review

#2472 Feature/sc 8447/add log filter
  CHANGELOG.md
  app.js
  controllers/alerts.js
  controllers/courses.js
  controllers/files.js
  controllers/helpdesk.js
  controllers/homework.js
  controllers/link.js
  controllers/login.js
  controllers/teams.js
  controllers/topics.js
  helpers/authentication.js
  helpers/csrf.js
  helpers/index.js
  helpers/logFilter.js
  helpers/timesHelper.js
  middleware/cors.js
  middleware/i18n.js
Labels: ready to merge, waiting for review

#2488 SC-8248 remove admin helpdesk functionality in schul cloud
  CHANGELOG.md
  controllers/help.js
  controllers/helpdesk.js
  controllers/index.js
  helpers/handlebars/middleware.js
  locales/de.json
  locales/en.json
  locales/es.json
  static/scripts/help/contactForm.js
  theme/n21/views/help/partials/help_form_button_label_proper_team_name.hbs
  theme/n21/views/lib/help_menu.hbs
  views/administration/forms/form-problem.hbs
  views/administration/helpdesk.hbs
  views/help/contact-card.hbs
  views/help/forms/form_admin.hbs
  views/help/partials/help_form_button_label_proper_team_name.hbs
  views/helpdesk/forms/form-problem.hbs
  views/helpdesk/helpdesk.hbs
  views/helpdesk/overview.hbs
  views/lib/help_menu.hbs
Labels: auto update, auto_merged, waiting for review

#2489 Feature/sc 8599 remodel help area contact page
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
  static/styles/help/help.scss
  static/styles/help/icon-card.scss
  views/help/contact-card.hbs
  views/help/forms/form_bug.hbs
  views/help/forms/form_wish.hbs
  views/help/partials/help_contact.hbs
Labels: auto update, do_not_merge, waiting for review

#2487 SC-8660 – remove teams and old job posting of dev ops from the footer
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
  theme/demo/views/lib/footer.hbs
  views/lib/extended_footer.hbs
  views/lib/extended_footer_links.hbs
  views/lib/footer.hbs
Labels: auto update, auto_merged, waiting for review

#2490 provide initial code for privacy message
  CHANGELOG.md
  controllers/dashboard.js
  package-lock.json
  package.json
  static/scripts/dashboard.js
  views/dashboard/dashboard.hbs
Labels: do_not_merge

#2483 SC-8409 Remove FAQ from help page
  CHANGELOG.md
  views/help/partials/help_about.hbs
Labels: auto update, ready to merge

#2486 SC-8595 follow up ticket to actualize gender language
  CHANGELOG.md
  controllers/administration.js
  controllers/homework.js
  helpers/content/team.js
  helpers/content/tutorials.json
  locales/de.json
  locales/en.json
  locales/es.json
  theme/brb/views/authentication/home.hbs
  theme/brb/views/dataprivacy/text_einwilligung-dv.hbs
  theme/brb/views/dataprivacy/text_intro.hbs
  theme/n21/views/dataprivacy/privacy_newsletter.hbs
  theme/n21/views/dataprivacy/privacy_rechte.hbs
  theme/open/views/authentication/home.hbs
  theme/open/views/dataprivacy/text_intro.hbs
  theme/open/views/dataprivacy/text_rechte.hbs
  theme/thr/views/about/about.hbs
  theme/thr/views/authentication/home.hbs
  theme/thr/views/dataprivacy/text_intro.hbs
  theme/thr/views/lib/no-create-info.hbs
  views/administration/forms/form-courses.hbs
  views/dataprivacy/text_datenverarbeitung-web.hbs
  views/dataprivacy/text_einwilligung-dv.hbs
  views/dataprivacy/text_helpdesk.hbs
  views/dataprivacy/text_intro.hbs
  views/dataprivacy/text_persbezogene-daten.hbs
  views/dataprivacy/text_rechte.hbs
  views/dataprivacy/text_speicherdauer.hbs
  views/dataprivacy/text_weitergabe-von-daten.hbs
  views/firstLogin/welcome.hbs
  views/teams/forms/form-add-member.hbs
Labels: auto update, auto_merged

#2491 Feature/sc 8599 follow up to remodel help area contact page
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
  static/scripts/help/contactForm.js
  views/help/contact.hbs
  views/help/forms/form_bug.hbs
  views/help/forms/form_wish.hbs
  views/help/partials/help_contact.hbs
Labels: auto update, do_not_merge, waiting for UX review

#2492 Feature/sc 6679 table structure properties
  CHANGELOG.md
  static/styles/lib/bootstrap/scss/_tables.scss
  views/topic/topic.hbs
Labels: auto update, waiting for review
