Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2021-08, with the labels that each got.

#2629 Add E2E test GitHub action
  .github/workflows/test_e2e.yml
Labels: run tests

#2627 SC-9074-wording change for Intern(al) Link in edit topic page
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
  static/scripts/topicEdit.js
Labels: run tests, waiting for test

#2628 Update dependencies
  package-lock.json
  package.json
Labels: run tests

#2634 SC-6071 changed wording on courses page
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
  views/courses/overview.hbs
Labels: run tests, waiting for review, waiting for test

#2626 divided share modal into separated forms
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
  static/scripts/courses.js
  static/scripts/files.js
  static/scripts/topic.js
  views/courses/course.hbs
  views/courses/forms/form-share.hbs
  views/files/files-grid.hbs
  views/teams/topics.hbs
  views/topic/topic.hbs
Labels: run tests, waiting for test

#2637 SC-9236 remove HPI footer logo
  CHANGELOG.md
  package-lock.json
  package.json
  theme/brb/views/lib/footer.hbs
  theme/thr/views/lib/footer.hbs
Labels: run tests

#2638 extended pull request template with QA check
  .github/PULL_REQUEST_TEMPLATE.md
Labels: run tests

#2639 SC-8165 showing a loading spinner during request for toggeling visibi…
  CHANGELOG.md
  static/scripts/courses.js
Labels: run tests

#2619 SC-9192 Fix path mapping
  CHANGELOG.md
  ansible/roles/schulcloud-client/templates/configmap.yml.j2
  config/global.js
  controllers/dashboard.js
  controllers/news.js
  controllers/teams.js
  helpers/apiHelper.js
  package-lock.json
  package.json
Labels: run tests

#2650 BC-64 - Fix e2e test branch selection bug
  .github/workflows/test_e2e.yml
Labels: waiting for review, run tests

#2648 Update tutorials.json
  helpers/content/tutorials.json
Labels: run tests

#2651 BC-64 BC-67 enable e2e tests for push on main
  .github/workflows/test_e2e_pull_request.yml
  .github/workflows/test_e2e_push_main.yml
  CHANGELOG.md
Labels: waiting for review, run tests

#2652 Feature/bc 14 change thr contact
  CHANGELOG.md
  theme/thr/views/lib/footer.hbs
Labels: waiting for review, run tests

#2653 BC-37 - BC-55 - reduce resource consumption for deployed client
  CHANGELOG.md
  ansible/roles/schulcloud-client/templates/deployment.yml.j2
Labels: waiting for review, run tests

#2659 bc-111 improve build pipeline further
  .github/workflows/build_push_service.yml
  .github/workflows/tag.yml
  Dockerfile
  scripts/unitTest.sh
Labels: run tests

#2655 BC-81 - remove old Lern-Store
  CHANGELOG.md
  config/default.schema.json
  config/development.json
  config/production.json
  controllers/content.js
  controllers/index.js
  helpers/handlebars/middleware.js
  test/mocha/content/content.test.js
  views/administration/school.hbs
  views/content/forms/form-add-lesson.hbs
  views/content/forms/form-external-link.hbs
  views/content/forms/form-search.hbs
  views/content/item.hbs
  views/content/store.hbs
Labels: run tests

#2661 BC-44
  CHANGELOG.md
  static/scripts/autologout.js
Labels: ready to merge, waiting for review, run tests
