Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2021-05, with the labels that each got.

#2532 SC-6950 - validation for officialSchoolNumber now allows 5-6 digits instead of 5
  CHANGELOG.md
  views/administration/school.hbs
Labels: ready to merge

#2534 Feature/sc 8599 UI adjustments of support contact page
  .github/workflows/require_changelog.yml
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
  static/styles/help/help.scss
  static/styles/help/icon-card.scss
  views/administration/school.hbs
  views/help/contact-card.hbs
  views/help/forms/form_bug.hbs
  views/help/forms/form_wish.hbs
Labels: ready to merge

#2386 Feature/ops 1559 enhance build pipeline
  .travis.yml
  CHANGELOG.md
  build.sh
  deploy.sh
Labels: waiting for review

#2425 SC-8342 Bug fixing show password button
  CHANGELOG.md
  locales/de.json
  locales/en.json
  static/styles/lib/bootstrap/scss/_input-group.scss
  views/account/settings.hbs
Labels: auto update, auto_merged, ready to merge

#2533 SC-8712 Fixing default text when assigning topics
  CHANGELOG.md
  locales/de.json
  locales/en.json
  views/homework/edit.hbs
Labels: waiting for UX review, waiting for review

#2542 SC-8730 Fixing sharing text for sharing whole course
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
Labels: waiting for UX review, waiting for review

#2535 SC-9040 Changing placeholder text in task
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
Labels: ready to merge

#2545 add additional check for email changes
  CHANGELOG.md
  controllers/account.js
  locales/de.json
  locales/en.json
  locales/es.json
  package-lock.json
  package.json
Labels: waiting for review

#2551 SC-9062 remove inline JS in homework section
  CHANGELOG.md
  config/http-headers.js
  package-lock.json
  package.json
  static/scripts/homework/assignment.js
  static/scripts/homework/edit.js
  views/homework/assignment.hbs
  views/homework/edit.hbs
Labels: auto update, waiting for review
