Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2021-03, with the labels that each got.

#2494 SC-8595 – add missing changes after testing
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
  theme/brb/views/authentication/home.hbs
  views/help/language-hint.hbs
Labels: auto update, auto_merged, waiting for review

#2496 Feature/SC-8599 - follow up fixed naming of Schul-Cloud to HPI Schul-Cloud
  CHANGELOG.md
  locales/de.json
  locales/en.json
Labels: auto update, ready to merge

#2497 SC-8595 remove linguistic note from help page correctly
  CHANGELOG.md
  theme/n21/views/help/help.hbs
  views/help/confluence.hbs
  views/help/contact.hbs
  views/help/help.hbs
Labels: auto update, ready to merge

#2500 feature/SC-8248 follow up to fix missing router.use in index.js
  CHANGELOG.md
  controllers/index.js
Labels: ready to merge

#2503 Release/26.0.2
  CHANGELOG.md
  config/default.json
  controllers/administration.js
  controllers/homework.js
  helpers/content/team.js
  helpers/content/tutorials.json
  locales/de.json
  locales/en.json
  locales/es.json
  package-lock.json
  package.json
  test/mocha/helpers/i18n.test.js
  test/mocha/i18n/i18n.test.js
  theme/brb/views/authentication/home.hbs
  theme/brb/views/dataprivacy/text_einwilligung-dv.hbs
  theme/brb/views/dataprivacy/text_intro.hbs
  theme/n21/views/dataprivacy/privacy_newsletter.hbs
  theme/n21/views/dataprivacy/privacy_rechte.hbs
  theme/n21/views/help/help.hbs
  theme/open/views/authentication/home.hbs
  theme/open/views/dataprivacy/text_intro.hbs
  theme/open/views/dataprivacy/text_rechte.hbs
  theme/thr/views/about/about.hbs
  theme/thr/views/authentication/home.hbs
  theme/thr/views/dataprivacy/text_intro.hbs
  theme/thr/views/lib/no-create-info.hbs
  views/administration/forms/form-courses.hbs
  views/dataprivacy/text_datenverarbeitung-web.hbs
  views/dataprivacy/text_einwilligung-dv.hbs
  views/dataprivacy/text_helpdesk.hbs
  views/dataprivacy/text_intro.hbs
  views/dataprivacy/text_persbezogene-daten.hbs
  views/dataprivacy/text_rechte.hbs
  views/dataprivacy/text_speicherdauer.hbs
  views/dataprivacy/text_weitergabe-von-daten.hbs
  views/firstLogin/welcome.hbs
  views/help/confluence.hbs
  views/help/contact.hbs
  views/help/help.hbs
  views/help/language-hint.hbs
  views/lib/forms/form-change-language.hbs
  views/teams/forms/form-add-member.hbs
Labels: waiting for review
