Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2021-04, with the labels that each got.

#2517 Hotfix/3/sc 8931 performance startpage
  CHANGELOG.md
  config/development.json
  controllers/alerts.js
  controllers/login.js
  controllers/schools.js
  helpers/cache/Cache.js
  helpers/cache/alert.js
  helpers/cache/index.js
  helpers/cache/schools.js
  package-lock.json
  package.json
  static/scripts/login.js
  test/mocha/helpers/cache.test.js
Labels: waiting for review

#2524 feature/sc 8170 legacy client footer links are in two lines
  CHANGELOG.md
  static/styles/lib/base.scss
Labels: waiting for review

#2525 SC-8668 - fixed small typo in manage school page
  CHANGELOG.md
  locales/de.json
Labels: ready to merge

#2526 SC-6323 & SC-8507 Fixed the less than 24 hours message and due date
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
  views/homework/assignment.hbs
  views/homework/components/course_overview_card_template.hbs
  views/homework/components/overview_card_template.hbs
Labels: ready to merge, waiting for review
