Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2021-12, with the labels that each got.

#2727 added data-testId to fix e2e test
  CHANGELOG.md
  views/courses/edit-course.hbs
Labels: waiting for review, run tests, run unstable tests

#2719 Feature/bc 609 finished tasks
  CHANGELOG.md
  locales/de.json
  locales/en.json
  locales/es.json
  views/courses/components/tasks.hbs
Labels: auto update

#2714 BC-617 Changes on instances for transition HPI -> Dataport
  CHANGELOG.md
  ansible/roles/schulcloud-client/templates/client-configmap-files.yml.j2
  ansible/roles/schulcloud-client/templates/configmap.yml.j2
  config/documents.js
  config/global.js
  config/http-headers.js
  controllers/administration.js
  helpers/content/schools.json
  helpers/partner/partners.json
  helpers/theme.js
  locales/de.json
  locales/en.json
  locales/es.json
  theme/brb/views/authentication/home.hbs
  theme/brb/views/lib/extended_footer_links.hbs
  theme/brb/views/lib/footer.hbs
  theme/thr/views/about/about.hbs
  views/administration/partials/data_protection_hint.hbs
  views/community/community.hbs
  views/help/lern-nuggets.hbs
  views/lib/extended_footer.hbs
Labels: waiting for review, run tests

#2726 BC-856-adjust-add-btn-on-topic
  CHANGELOG.md
  static/scripts/topicEdit.js
Labels: waiting for review, run tests

#2729 BC-855-adjust-footer
  CHANGELOG.md
  theme/thr/views/lib/footer.hbs
Labels: waiting for review, run tests

#2730 BC-741 - Split and sort ansible rols
  CHANGELOG.md
  ansible/roles/schulcloud-client-core/tasks/main.yml
  ansible/roles/schulcloud-client-core/templates/client-configmap-files.yml.j2
  ansible/roles/schulcloud-client-core/templates/configmap.yml.j2
  ansible/roles/schulcloud-client-core/templates/deployment.yml.j2
  ansible/roles/schulcloud-client-core/templates/onepassword.yml.j2
  ansible/roles/schulcloud-client-core/templates/secret.yml.j2
  ansible/roles/schulcloud-client-core/templates/svc.yml.j2
  ansible/roles/schulcloud-client-ldap/tasks/main.yml
  ansible/roles/schulcloud-client-ldap/templates/deployment.yml.j2
  ansible/roles/schulcloud-client-ldap/templates/svc.yml.j2
Labels: waiting for review

#2734 BC-744 - BC-935 - Update the ansible group and host vars
  ansible/group_vars/all/schulcloud-client.yml
  ansible/group_vars/brb/schulcloud-client.yml
  ansible/group_vars/default/schulcloud-client.yml
  ansible/group_vars/develop/schulcloud-client.yml
  ansible/group_vars/nbc/schulcloud-client.yml
  ansible/group_vars/reference/schulcloud-client.yml
Labels: waiting for review

#2736 BC-781 - Update deploy and clean github workflow
  .github/workflows/clean.yml
  .github/workflows/push.yml
Labels: waiting for review

#2733 Feature/bc 643 hide old task overview
  controllers/homework.js
  helpers/handlebars/middleware.js
  locales/de.json
  locales/en.json
  locales/es.json
  test/mocha/homework/homework.test.js
Labels: run tests

#2737 change naming in contact area
  locales/de.json
  locales/en.json
  locales/es.json
  views/help/forms/form_bug.hbs
  views/help/forms/form_wish.hbs
Labels: waiting for review, run tests
