Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2021-07, with the labels that each got.

#2592 SC-9159 use news v3
  controllers/dashboard.js
  controllers/news.js
  controllers/teams.js
  views/news/article.hbs
Labels: WIP

#2610 SC-9124 Add feature flags to configmap
  CHANGELOG.md
  ansible/roles/schulcloud-client/templates/configmap.yml.j2
Labels: waiting for review

#2611 OPS-2574 - Removeing autodeployed branches for developers if branch deleted
  .github/workflows/clean.yml
  CHANGELOG.md
Labels: waiting for review

#2614 Start rabbitMq for unit tests
  scripts/unitTest.sh
Labels: ready to merge

#2613 fixed submissions overview
  CHANGELOG.md
  static/styles/homework/submissions.scss
Labels: waiting for review

#2615 OPS-2579 - change path to the sotrage.
  CHANGELOG.md
  ansible/roles/schulcloud-client/templates/client-configmap-files.yml.j2
Labels: waiting for review
