Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2022-07, with the labels that each got.

#2909 Feature/bc 1502 switch handling of task files
  controllers/files-storage.js
  controllers/homework.js
  helpers/files-storage.js
  locales/de.json
  locales/en.json
  locales/es.json
  locales/ua.json
  static/scripts/files-storage.js
  static/styles/files/upload.scss
  test/mocha/homework/homework.test.js
  views/homework/assignment.hbs
  views/homework/edit.hbs
  views/homework/extended.hbs
  views/lib/components/files-storage/file-upload.hbs
  views/lib/components/files-storage/files-card.hbs
  views/lib/components/files-storage/files-grid.hbs
  views/lib/components/files-storage/files.hbs
  views/lib/components/files-storage/forms/form-name-edit.hbs
Labels: do_not_merge

#2915 BC-1504 Use v3 route to delete task
  controllers/homework.js
Labels: waiting for review

#2940 BC-2092 – delete copy button task detail view
  controllers/homework.js
  views/homework/extended.hbs
Labels: auto update, run tests

#2943 BC-2149 - new task: keep textarea in sync with ckeditor
  static/scripts/ckeditor/ckeditor.js
Labels: waiting for review

#2947 N21-252 Changed info texts for videoconferences
  locales/de.json
  locales/en.json
  locales/es.json
  locales/ua.json
Labels: waiting for review
