Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2022-04, with the labels that each got.

#2813 BC-1461 - Implement task functions into rooms view
  controllers/homework.js
Labels: waiting for review

#2799 Feature/ew 157 change own password refactoring
  controllers/account.js
  controllers/forcePasswordChange.js
Labels: waiting for review, javascript

#2818 BC-1617 - language feature toggle
  locales/de.json
  locales/en.json
  locales/es.json
  locales/ua.json
  package-lock.json
  package.json
  views/lib/forms/form-change-language.hbs
  views/lib/loggedin.hbs
  views/user/forms/language.hbs
Labels: ready to merge

#2827 BC-1578 Adjustment on Links to the help-area
  controllers/help.js
  helpers/handlebars/middleware.js
  locales/en.json
  locales/es.json
  static/styles/help/dashboard.scss
  views/help/dashboard.hbs
  views/lib/help_menu.hbs
Labels: waiting for review

#2825 BC-1634 - Move code for the neXBoard api from the nexboard-api-js package to this reposetory
  controllers/topics.js
  helpers/nexboard.js
  package-lock.json
  package.json
Labels: waiting for review

#2778 Feature/n21 32 new login GUI
  controllers/login.js
  locales/de.json
  locales/en.json
  locales/es.json
  locales/ua.json
  static/scripts/login.js
  static/styles/authentication/home.scss
  static/styles/homepage/login.scss
  test/mocha/login/login.test.js
  views/authentication/forms/login.hbs
Labels: ready to merge

#2786 Feature/n21 51 custom login link
  controllers/login.js
  static/scripts/login.js
  static/styles/authentication/home.scss
  static/styles/homepage/login.scss
  views/authentication/forms/login.hbs
Labels: do_not_merge

#2834 BC-1667 - remove auto reviewer assignment by pullapprove
  .pullapprove.yml
Labels: waiting for review

#2833 Feature/bc 1642 translations for calendar and relative timestamps
  controllers/news.js
  helpers/i18n.js
  locales/calendar/ua.json
  static/scripts/calendar.js
Labels: waiting for review

#2828 EW-165 Api route refactoring for the account endpoint
  controllers/administration.js
  views/administration/users_edit.hbs
Labels: waiting for review, javascript

#2822 BC-1393 - Replace current course detail page
  controllers/coursegroups.js
  controllers/courses.js
  controllers/files.js
  controllers/topics.js
  locale/ua.json
  locales/de.json
  locales/en.json
  locales/es.json
  locales/ua.json
  static/styles/lib/tabbar/tabbar.scss
  views/courses/course.hbs
  views/homework/assignment.hbs
  views/teams/team.hbs
Labels: waiting for review

#2836 BC-1675-password-showing-not-working
  views/authentication/forms/login.hbs
Labels: ready to merge

#2838 BC-1386: Missing active state on Courses
  config/default.schema.json
  controllers/courses.js
  helpers/handlebars/middleware.js
  static/styles/lib/loggedin.scss
  views/courses/create-course.hbs
Labels: waiting for review

#2840 BC-1700 - Password login button has wrong size
  static/styles/lib/bootstrap/scss/_input-group.scss
Labels: waiting for review

#2844 BC-1711 - Redirect after task creation in lesson does not work
  views/courses/components/tasks.hbs
  views/topic/topic.hbs
Labels: waiting for review
