Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2022-09, with the labels that each got.

#2944 BC-1951 Add info to text topic
  controllers/topics.js
  locales/de.json
  locales/en.json
  locales/es.json
  locales/ua.json
  static/scripts/ckeditor/plugins/ckeditor5-filebrowser/src/audio-browser-command.js
  static/scripts/ckeditor/plugins/ckeditor5-filebrowser/src/file-browser-helper.js
  static/scripts/ckeditor/plugins/ckeditor5-filebrowser/src/file-browser-modal.js
  static/scripts/ckeditor/plugins/ckeditor5-filebrowser/src/filebrowser.js
  static/scripts/ckeditor/plugins/ckeditor5-filebrowser/src/image-browser-command.js
  static/scripts/ckeditor/plugins/ckeditor5-filebrowser/src/video-browser-command.js
  static/scripts/files-storage.js
  static/scripts/helpers/storage.js
  static/scripts/topicEdit.js
  static/styles/topics/topics.scss
  views/topic/edit-topic.hbs
Labels: do_not_merge

#2971 BC-2422 - Display more than 25 coursegroups in groups tab of courses
  controllers/courses.js
Labels: waiting for review

#2980 EW-224 Frontend - OAuth Brokering via ErWIn IDM
  controllers/login.js
  locales/de.json
  locales/en.json
  locales/es.json
  locales/ua.json
  static/styles/authentication/home.scss
  static/styles/homepage/login.scss
  theme/brb/static/styles/authentication/home-login.scss
  theme/brb/views/authentication/home.hbs
  views/authentication/forms/login.hbs
Labels: blocked_by_server_pr
