Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2022-02, with the labels that each got.

#2757 BC-1202 - Fix missing ldap at some metadata
  ansible/roles/schulcloud-client-ldap/templates/deployment.yml.j2
Labels: waiting for review

#2758 BC-1202 - Fix Storage at the ansible rolle
  ansible/roles/schulcloud-client-core/templates/client-configmap-files.yml.j2
Labels: waiting for review

#2759 BC-1230 - change mode for configmaps to apply
  ansible/roles/schulcloud-client-core/tasks/main.yml
Labels: waiting for review

#2754 Feature/n21 9 oauth iserv flow
  config/default.schema.json
  controllers/login.js
  locales/de.json
  locales/en.json
  locales/es.json
  static/scripts/login.js
  test/mocha/helper/login-helper.js
  views/authentication/forms/login.hbs
Labels: waiting for review

#2766 BC-1282 - add frameSrc to the CSP Rules
  ansible/roles/schulcloud-client-core/templates/client-configmap-files.yml.j2
Labels: waiting for review

#2767 BC-1302 - set the default docker registry for all, will be overwritten for develop
  ansible/group_vars/all/schulcloud-client.yml
  ansible/group_vars/reference/schulcloud-client.yml
Labels: waiting for review

#2768 Feature/n21 39 iserv oauth hotfix
  controllers/login.js
Labels: ready to merge

#2769 version 27.6.0
  package-lock.json
  package.json
Labels: waiting for review

#2764 update hotfix version numbers in dependency to reduce follow-redirect…
  package-lock.json
  package.json
Labels: run tests

#2770 further infos of brb replaced below login
  locales/de.json
  locales/en.json
  locales/es.json
  theme/brb/views/authentication/home.hbs
Labels: waiting for review

#2771 small text changes
  locales/de.json
  locales/en.json
  locales/es.json
Labels: waiting for review

#2772 BC-1334 - add nexboard to frame source for courses
  ansible/roles/schulcloud-client-core/templates/client-configmap-files.yml.j2
Labels: waiting for review
