Repository hpi-schul-cloud/schulcloud-client, pull requests merged in 2022-05, with the labels that each got.

#2837 Bc 1579 general helparea for nbc
  config/default.schema.json
  config/global.js
  helpers/handlebars/middleware.js
  theme/brb/views/help/partials/help_nutzungshilfen.hbs
  theme/n21/views/help/help.hbs
  theme/n21/views/lib/help_menu.hbs
  theme/open/views/help/partials/help_nutzungshilfen.hbs
  theme/thr/views/help/partials/help_nutzungshilfen.hbs
  views/help/help.hbs
  views/help/partials/help_nutzungshilfen.hbs
  views/lib/help_menu.hbs
Labels: waiting for review

#2845 BC-1722 - Deleting task from task detail leading to error
  views/homework/extended.hbs
Labels: waiting for review

#2829 BC-1614 Refactor env-vars for student-visibility
  config/default.schema.json
  controllers/administration.js
  views/administration/school.hbs
Labels: waiting for review

#2847 BC-1736-fixed broken language key in teams administration
  locales/de.json
  locales/en.json
  locales/es.json
  locales/ua.json
  views/administration/forms/form-message-owner.hbs
Labels: waiting for review

#2856 BC-1687 - remove open from code base
  .github/workflows/push.yml
  .github/workflows/tag.yml
  controllers/dataprivacy.js
  theme/open/static/images/favicon.ico
  theme/open/static/images/logo/app-icon-120.png
  theme/open/static/images/logo/app-icon-128.png
  theme/open/static/images/logo/app-icon-144.png
  theme/open/static/images/logo/app-icon-148.png
  theme/open/static/images/logo/app-icon-152.png
  theme/open/static/images/logo/app-icon-167.png
  theme/open/static/images/logo/app-icon-180.png
  theme/open/static/images/logo/app-icon-192.png
  theme/open/static/images/logo/app-icon-48.png
  theme/open/static/images/logo/app-icon-512.png
  theme/open/static/images/logo/app-icon-72.png
  theme/open/static/images/logo/app-icon-96.png
  theme/open/static/images/logo/cloud-transparent-mono-48-48.svg
  theme/open/static/images/logo/cloud-transparent-mono.svg
  theme/open/static/images/logo/favicon-16.png
  theme/open/static/images/logo/favicon-32.png
  theme/open/static/images/logo/favicon-36.png
  theme/open/static/images/logo/favicon-48.png
  theme/open/static/images/manifest.json
  theme/open/static/robots.txt
  theme/open/style.scss
  theme/open/views/authentication/home.hbs
  theme/open/views/dataprivacy/privacy.hbs
  theme/open/views/dataprivacy/privacy_guests.hbs
  theme/open/views/dataprivacy/text_datenverarbeitung-schulen.hbs
  theme/open/views/dataprivacy/text_intro.hbs
  theme/open/views/dataprivacy/text_rechte.hbs
  theme/open/views/help/lern-nuggets.hbs
  theme/open/views/help/mail-card.hbs
  theme/open/views/help/people.hbs
  theme/open/views/lib/extended_footer.hbs
  theme/open/views/lib/footer.hbs
  theme/open/views/lib/header.hbs
  theme/open/views/lib/simple.hbs
  theme/open/views/registration/forms/einwilligungserklaerung.hbs
  views/help/partials/login_failed_hint.hbs
Labels: waiting for review

#2858 BC-1723 Add NO_COLOR Environment variable.
  config/default.schema.json
Labels: waiting for review

#2860 BC-1748: Provide accessibility changes in footer
  config/default.schema.json
  config/documents.js
  locales/de.json
  locales/en.json
  locales/es.json
  locales/ua.json
  theme/brb/views/lib/extended_footer.hbs
  theme/brb/views/lib/extended_footer_links.hbs
  theme/brb/views/lib/footer.hbs
  theme/n21/views/lib/extended_footer.hbs
  theme/n21/views/lib/footer.hbs
  theme/thr/views/lib/extended_footer.hbs
  theme/thr/views/lib/footer.hbs
Labels: waiting for review

#2869 BC-1803 - Table of contents in help area on mobile
  static/styles/help/help.scss
  theme/thr/views/help/partials/help_about.hbs
  views/help/icon-card.hbs
  views/help/partials/help_about.hbs
  views/help/partials/help_confluence_links.hbs
  views/help/partials/help_first_steps.hbs
  views/help/partials/help_nutzungshilfen.hbs
Labels: waiting for review

#2870 BC-1783 - clean up public tech documentation
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: waiting for review

#2872 BC-1816 - Icon in calendar too big
  static/scripts/calendar.js
  static/styles/calendar/calendar.scss
Labels: waiting for review

#2843 Feature/ew 166 refactor user functionality
  controllers/administration.js
Labels: blocked_by_server_pr, javascript

#2871 BC-1484 Fix empty calendar dropdown menu
  controllers/courses.js
  static/scripts/calendar.js
  views/calendar/forms/form-create-event.hbs
Labels: ready to merge
